### ISSUE TITLE
lively ought to have version and build available

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#10]
It really helps in error reporting.  This should also give node and npm information if available (this is really to help the developers when bugs are reported)

**Comment by frcroth** [comment]
Partially fixed with https://github.com/LivelyKernel/lively.next/commit/0f8c092578f0131d7da67e853648e1f975fd8d58

**Comment by merryman** [comment]
I think should be fully fixed by now!
