### ISSUE TITLE
Several Issues with Reconciliation

### ISSUE THREAD

**Issue by merryman** [LivelyKernel/lively.next#1023]
Fix #982 :heavy_check_mark: 
 - [x] Imports that are inserted into a component module due to reconciliation are always absolute. It is better practice to turn them into relative imports in case they originate from the same project.
 - [x] There are issues with moving components around that lead to dropped `add()` calls or the incorrect creation of duplicate morphs (if they are moved down the morph hierarchy). :heavy_check_mark: 
 - [x] Live propagation among derived components and instances appears to be broken. I am pretty sure the `isDerivedFrom` check is failing for some reason. :heavy_check_mark: 
 - [x] reconciliation of effect properties is still broken. They sometimes insert `[object object]` strings into the code (cursor). :heavy_check_mark: 
 - [x] reconciliation of border removal via side bar does not do anything it seems. :heavy_check_mark: 
 - [x] reconciliation of chaning the height/width policy of text morphs inside the tiling layout is somewhat broken. It for instance does not reconcile the `fixedHeight` or `fixedWidth` property correctly when it is set to `hug` :heavy_check_mark: 
 - [ ] Structural changes in parent components should be reconciled in a more smart way. Right now nothing happens, which is maybe the worst of all worlds, leading to broken derived component definitions.

**Comment by linusha** [comment]
Reconciliation of masters via the new sidebar controls does not work.
