### ISSUE TITLE
Shape menu is incorrectly layoutet when first opened

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#1039]
**Describe the bug**
When the shape menu is opened for the first time, it is layouted incorrectly. It looks correct on subsequent openings. 

**Screenshots**
![image](https://github.com/LivelyKernel/lively.next/assets/14252419/c3b3b9bd-95b0-4d85-a9ef-2bc698c1a0c5)

**Version**: a99bdced68f99a5152c9c39f17b7f60174deca50

**Comment by merryman** [comment]
This was supposed to be fixed in #1031. I wonder what happened in between.
