### ISSUE TITLE
Editing text with `fixedWidth` should scroll the text content

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#1043]
**Describe the Feature**
When entering text into a text morph that has a `fixedWidth` as well as a `fixedHeight` and the text gets too long to fit into the morph, the text should "scroll" with the cursor position. This is what other GUI toolkits do. 

Currently, the cursor and the text just "disappear".

**Comment by linusha** [comment]
This works. However, it is necessary to set the properties as follows:
- `fixedWidth` and `fixedHeight` needs to be set to `true`
- `clipMode` needs to be set to `hidden`
- `lineWrapping` needs to be set to `no-wrap`.

See for example the `InputLine` for a demonstration of this behavior working.

**Comment by linusha** [comment]
Investigating further, the `lineWrapping` value might not be relevant. However, I found another bug, will update.

**Comment by linusha** [comment]
Alright, so it is necessary to fix the width and the height via the properties. This makes sense imo.
Additionally, it is important to set the clipMode of the text to `hidden`.
With `visible`, the text just disappears, but also does never extent beyond the morph. I think this is a bug too? 😧 
What do you think, @merryman?

**Comment by merryman** [comment]
Since #1398 is now ready, is this issue still applicable?
