### ISSUE TITLE
Text Editing on System Button is hard

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#1052]
**Describe the bug**
Not exactly sure if this is a bug per se, or more an edge-case that we have not thought through. When editing text on a SystemButton, one cannot select text via the mouse. This is, I believe, partially due to the custom master states that are triggered on click, but there is something other at work as well. 

**Screenshots**

![text_editing_on_system_button](https://github.com/LivelyKernel/lively.next/assets/14252419/c8215d97-733c-4fd4-b13f-1830eb4b5715)

**With clicked state removed:**

![text_editing_without_clicked_state](https://github.com/LivelyKernel/lively.next/assets/14252419/97c53aef-22dd-492c-9457-9c04c8d8abda)

**Version**: 736f912ff2c836825269ab01e92403fbae7a7903

**Comment by merryman** [comment]
I think this is simply because the label has `reactsToPointer` set to `false`. We can think about the halo temporarily switching this property to `true` for the sake of editing/
