### ISSUE TITLE
Loading components failing

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#106]
In world dashboardStudioOne, I've created a component, unitBox, and when I attempt to load it with:
let a = resource('part://dashboardStudioOne/unitBox');
let m, err;
a.read().then(morph => m = morph, e=> err = e);
e is TypeError: Cannot read property 'mastersInSubHierarchy' of undefined

**Comment by merryman** [comment]
Did you actually save the world dashboardStudioOne, before you wanted to import it?

**Comment by merryman** [comment]
OK, I took a look at the word. The problem is that you have assigned the name of the master component to other morphs inside the world that are not components. That is a name collision which should have been captured by the system. I will add a check for that in the halo.
