### ISSUE TITLE
Text align button on sidebar doesn't work for labels

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#107]
See the attached screenshot
![image](https://user-images.githubusercontent.com/656259/100294633-3fcee900-2f3c-11eb-8cf0-950b92cde593.png)

**Comment by merryman** [comment]
Labels do not support textAlign. This is a bug inside the side bar, which should not display those options in the first place.

**Comment by merryman** [comment]
This is fixed now accordingly in ec0ed59716bcb891e2340c95fbdc204923a3ba3f
