### ISSUE TITLE
I get a Halo around an underlying morph when trying to open the sidebar on the Object Editor

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#11]
See this screenshot.  I pulled up the OE on the cytoscape morph, clicked on the arrow to open up the CytoscapeMorph code, and instead got a halo around the underlying Cytoscape morph.  See the attached screenshot.
![image](https://user-images.githubusercontent.com/656259/96187369-badec180-0ef1-11eb-9804-11a48b0c2763.png)

**Comment by merryman** [comment]
Yes, I think the halo hover feature should be disabled when hovering over windows. I will ad that as a feature. The tradeoff is of course that you can not really hover inspect any morphs inside windows any more, but I guess that is alright.

**Comment by merryman** [comment]
I have trouble reproducing this behavior actually. Can you try reproducing this issue on a clean world?
