### ISSUE TITLE
Loading a new project is broken

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#1110]
**Describe the bug**
On loading a new project, we get to this point:
![image](https://github.com/LivelyKernel/lively.next/assets/656259/72763919-0f48-40fd-b25f-da88b182e997)

and then the system hangs.  Opening up the browser console shows this error:

```
__rootModule___commonjs-entry-0ee7f132.js:175 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertySymbols (<anonymous>)
    at Window.prepareSystem (system.js:185:12)
    at execute (index.js:353:184)
    at ensureEvaluated (system.src.js:3363:26)
    at Object.execute (system.src.js:3513:13)
    at doDynamicExecute (system.src.js:766:25)
    at link (system.src.js:964:20)
    at doLink (system.src.js:623:7)
    at updateLinkSetOnLoad (system.src.js:669:18)
    at system.src.js:485:11
```

**To Reproduce**
Choose "New Project" from the boot screen

**Screenshots**

**Setup**
Please delete non-applicable items!

- Windows
- Linux

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).
commit 7489cd9c9a58534a10133a74865d15ec1f6d36e3

**Comment by rickmcgeer** [comment]
I traced this in the console debugger, the offending call is:
```
Object.getOwnPropertySymbols(System.registry)
```
line 185 in system.js

`System.registry` is undefined

**Comment by linusha** [comment]
@rickmcgeer please run the `./install.sh` script.

**Comment by rickmcgeer** [comment]
Great minds think alike!  @linusha I did that and it resolved the issue.
