### ISSUE TITLE
Editing a Morph brings up a "No module source" dialog

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#1115]
**Describe the bug**
Clicking on the wrench icon on the halo brings up an error, that there is no module source for the component

**To Reproduce**
1. Create a new project
2. Create a morph (e.g, a rectangle)'
3. Bring up a halo
4. . Click on the wrench icon

**Screenshots**
![Screenshot 2023-11-28 072419](https://github.com/LivelyKernel/lively.next/assets/656259/b928588f-e8d5-4352-ad8f-3dc79462f302)

**Setup**
Please delete non-applicable items!

- Windows
- Linux

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).
7489cd9c9a58534a10133a74865d15ec1f6d36e3

**Comment by merryman** [comment]
This is already fixed in #1099.
