### ISSUE TITLE
HTML Morph Vertically Misaligned

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#113]
See the image.  The HTML is about 20px below the top of its container.
![image](https://user-images.githubusercontent.com/656259/101058302-d9505900-3541-11eb-818a-11a3d4146acd.png)

**Comment by merryman** [comment]
This is because of your usage of h1 tags. This again confirms my rather dubious stance of embracing HTML like this. It creates all kinds of issues like that while the point of lively is exactly: not to have them in the first place.

**Comment by rickmcgeer** [comment]
I used <p> tags and the issue persisted:
![image](https://user-images.githubusercontent.com/656259/101081183-9650ae80-355e-11eb-9e88-e4b02557ac25.png)

**Comment by merryman** [comment]
Don't use paragraphs either. Once you use div it will be fine.
