### ISSUE TITLE
Text highlighting persists, for no reason I can understand

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#115]
I tried looking at the properties to see why, but nothing is showing up in the styling palette or the inspector

![image](https://user-images.githubusercontent.com/656259/101060654-80ce8b00-3544-11eb-8e41-cb3067d8d09f.png)

**Comment by linusha** [comment]
Is this a component that you load from another world? We saw the same thing happening to us yesterday, when we had some text selected in our component when we saved the world, the selection later persisted in another world where we loaded the component. Unselecting the text in the original component and saving the world again fixed it for us.

**Comment by merryman** [comment]
The selection layer is not persisted by the master component update mechanism. However it is persisted upon serialization. We can discuss if we want to always discard selection on serialization. Thoughts?

**Comment by rickmcgeer** [comment]
Thanks, clicking on it solved it; maybe there was nothing here and you can close it out.  It just wasn't obvious to me that that was what to do, but maybe it would be to most people
