### ISSUE TITLE
Source Code Revival Bugs

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#1155]
There are situations where the source code revival does not work as expected, making a rebuild of the bundle necessary to apply changes.

One of these situations can be seen when building on https://github.com/LivelyKernel/lively.next/tree/enhancement/proportional-css-layouts and then checking out https://github.com/LivelyKernel/lively.next/tree/fix/edit-prompt-open-and-confirm, where the changes will not be applied.

@merryman feel free to add to this/rewrite as necessary!

**Comment by merryman** [comment]
Current issue on my agenda is to enhance the source transform such that it is able to properly capture variable declarations, such that injected variables can correctly populate the bundle.
