### ISSUE TITLE
Text morphs shouldn't accept drops by default

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#116]

**Comment by merryman** [comment]
I think this goes into a general revision of the Label/Text system we have in place right now.
A couple of ideas:
1.) Users should not have to choose between Labels and Texts. Rather the system should be deciding for them what is right.
2.) Text Morphs themselves are extremely large and carry a lot of overhead (embedded morphs, document index) for all the convenience that is often not needed. I suggest introducing an intermediate mode that would satisfy 90% of the cases where texts are used. In there we skip all of the editing capabilities and just render a text morph's rich text without inspection capabilties. That would drastically improve memory footprint and serialization performance.

**Comment by linusha** [comment]
> I think this goes into a general revision of the Label/Text system we have in place right now.
> A couple of ideas:
> 1.) Users should not have to choose between Labels and Texts. Rather the system should be deciding for them what is right.
> 2.) Text Morphs themselves are extremely large and carry a lot of overhead (embedded morphs, document index) for all the convenience that is often not needed. I suggest introducing an intermediate mode that would satisfy 90% of the cases where texts are used. In there we skip all of the editing capabilities and just render a text morph's rich text without inspection capabilties. That would drastically improve memory footprint and serialization performance.

I do not know if there is some kind of prioritization in here, I just wanted to add that these are things that also came up during the user testing for our project. I fear that we will not be able to tackle it in there, since we are rapdily approaching the end of the programming time, but therefore this may be a good candidate for further work in the months after the whole project has ended. :)
