### ISSUE TITLE
Morphs missing from scene graph on sidebar

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#117]
I suspect this is an issue with windows.  I put cubePanel in a window, and then took it out -- but now it's not appearing in the scene graph in the left-hand sidebar.  This is an issue because there's no other way to edit existing connections with this or its submorphs.
![image](https://user-images.githubusercontent.com/656259/101117220-65429f00-359b-11eb-804b-38b8ba6226bb.png)

**Comment by rickmcgeer** [comment]
whatever caused it, when I saved and reloaded the object re-appeared in the scene graph.

**Comment by merryman** [comment]
Hmm definitely bug. I will try to reproduce.

**Comment by merryman** [comment]
I have no way to reproduce this, so I will close this for now. If nothing like this reappears it has probably been resolved by now.
