### ISSUE TITLE
Fill isn't copied on submorphs when morphs are copied between using the clipboard

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#118]
I copied chartHolder from an old version of DashboardStudioThree I had open (just for this purpose) to a current version of the world, and in the original world the contained chart had a fill of rgb(255,255,255), and in the copy it had a fill of rgba(0,0,0,0)

**Comment by merryman** [comment]
I am quite sure this is a problem with master components, not morphs per se.
