### ISSUE TITLE
No code pane in the Object Editor!

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#12]
See attached screenshot.  When I killed the editor and brought up a new one from the halo is was fine.
![image](https://user-images.githubusercontent.com/656259/96187820-83244980-0ef2-11eb-8540-bb20eb735a7e.png)

**Comment by merryman** [comment]
This is probably an issues with some of the master components responsible for styling object editor... It looks like the code editor is there but just extremely small (upper left hand corner). I can not really reproduce this bug, but there are some other issues with master components not knowing the difference between extent, height or width. Maybe that is related. Lets see what happens once I fix those issues.
