### ISSUE TITLE
World names are blocked longer than the worlds exist

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#121]
I had a world named test. Yesterday I deleted it. I have since restarted the server. Upon restarting the server and creating a new world, the name test was still blocked, i.e. I got the pop-up that the name is already taken and I should pick another one.

I expected the list of blocked names to be consistent with the list of world names I can see in my Dashboard.

**Comment by merryman** [comment]
These worlds are currently not "hard" but "soft" deleted. I will look into this again, maybe we should just permanent delete for now by default when we operate in the world list....

**Comment by linusha** [comment]
This is circumvented since 5ea4964e1c0a40644cfc70ac46efb07b286d28a1.
