### ISSUE TITLE
Revival Propagation fails for common lively.lang usecase

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#1235]
I added a function to `lively.lang/array.js` and exported that at the bottom, as we usually do in lively.lang. When starting a new session, the console logged correctly, that `lively.lang/array.js` was revived. Importing my new function from `array.js` directly worked. However, the `arr` object, exposed via `lively.lang/index.js` was not updated on the fly, so that I could not do `arr.myCoolNewFunction()`. After I executed the `arr` population inside of `lively.lang/index.js`, everything worked as expected.

**Comment by merryman** [comment]
That's very strange. It should have been fixed with #1179, but somehow it slipped through the cracks? I will see.
