### ISSUE TITLE
File Browser cannot be opened

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#1259]
Error: Fetch error: 404 Not Found
  Instantiating http://localhost:9011/dashboard/http-file-browser-dfaabe27.js
  Loading ./http-file-browser-dfaabe27.js
Error: Fetch error: 404 Not Found
    at http://localhost:9011/dashboard/deps.js:3426:15

**Comment by merryman** [comment]
I can not reproduce this locally. Looking at the stack trace, I am 99% certain that you rebuild the landing/loading page but forgot to reload the lively session.

**Comment by linusha** [comment]
My bad, sorry.
