### ISSUE TITLE
Can't make a connection to a containing morph

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#127]
GoogleChartHolder has two submorphs, GoogleCharts and ChartControl.  I can make a connection to either of the submorphs, but the connection targeter won't let me select the containing morph.  I can do this with code, of course, but the drag-and-drop UI could use some work (maybe select the target in the scene graph sidebar?)

**Comment by merryman** [comment]
You can select the morph as a target in the scene graph as well :-)
