### ISSUE TITLE
Weirdest behavior I have ever seen

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#128]
The following code:
get configuration() {
   const filters = this.getSubmorphNamed('filterPanel').filters;
  return {internalFilters: filters}
}
returns an empty object
The following code, however, returns what I expect:
get configuration() {
   const filters = this.getSubmorphNamed('filterPanel').filters;
  return {foo: filters}
}
Is this JavaScript, Lively, or something weird?

**Comment by merryman** [comment]
Are these the same method on 2 different objects?

**Comment by merryman** [comment]
Can this be closed?
