### ISSUE TITLE
Saving world crashed process.  

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#131]
I deleted a bunch of windows from DashboardStudioThree and tried to resave, but the process crashed midway.  Fortunately, I was able to reload the world, and no damage done (collapsed windows were still there).  No information on how or why.

**Comment by rickmcgeer** [comment]
Re-saved and it worked.  Will let you know if it happens again.

**Comment by merryman** [comment]
This happens when the chrome process exceeds a certain amount of memory (my guess is like 2GB). We currently have a couple of memory leaks in the system that cause memory to be leaked over time.
I will look into this once I find some time.

**Comment by linusha** [comment]
Closing this as stale for now.
