### ISSUE TITLE
Editor windows (Object Editor, HTML Editor) displaced off screen at opening

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#134]
![image](https://user-images.githubusercontent.com/656259/102549171-88c41a00-4070-11eb-8391-31e0d0c1290f.png)

**Comment by rickmcgeer** [comment]
The world is: https://matt.engagelively.com/worlds/load?name=GoogleChartTest

**Comment by merryman** [comment]
This has started to happen to me recently too. @linusha Do you think this is somewhat related to the new bounds computation for aligning windows insider the world? I believe you introduced a new method that was factoring in the top bar.

**Comment by merryman** [comment]
Fixed now in 191a6e0d3cec4326f14bd146394c9e8394461eb7
