### ISSUE TITLE
World Menu should be in the top bar

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#1383]
**Describe the Feature**
The world menu is only available by right-clicking on the studio.  But this makes it unavailable when the studio background is covered in other windows.  This is particularly the case when I'm building an application and I want the application to take over the entire studio; but it happens less dramatically at other times, like when I have a bunch of browsers and workspaces open.
**Graphics**
A classic example is the Burger or dots menu in most web applications.  GMail, for example, has a burger menu in the top left and a matrix-dot menu for other applications in the top right; VSCode has a list of menu types in the left sidebar

**Implementation Details**
The simplest version is just one more icon in the top bar that pops up the current world menu

**Comment by linusha** [comment]
We actually have implemented this upon an earlier request by you, see #743. :slightly_smiling_face:  

Your `localconfig.js` needs to look like this to enable it:
```
import { config } from "lively.morphic";

config.ide.studio.worldMenuInTopBar = true
```
