### ISSUE TITLE
Worlds are now all owned by robin.schrieber

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#14]
![image](https://user-images.githubusercontent.com/656259/96304277-ab727d80-0fb0-11eb-83be-592370b78445.png)

**Comment by merryman** [comment]
This bug is probably due to a missing check for if the user menu is present or not. We lazy load that now. That missing check causes the display routine of the user flap to fail and it always displays the default, which happens to be my account :-). Will fix.

**Comment by merryman** [comment]
Should be fixed now in b47c0c7c52a1313677eccd8dd06e8f5840a0fe39
