### ISSUE TITLE
Can't tell what's going on with connections

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#140]
I created a connection between a button and a local method, but now when I look at it on the scene graph the connection seems to be to nothing.  See this screenshot:
![Screen Shot 2020-12-29 at 15 24 54](https://user-images.githubusercontent.com/656259/103320561-a25b4f00-49ea-11eb-9c21-fa276d324221.png)
Is this a bug in rendering, did the connection somehow get busted?  I don't know.  Moreover, when I look at it, this is what I see:
![image](https://user-images.githubusercontent.com/656259/103320626-f7976080-49ea-11eb-9725-f0cacd84973d.png)
which doesn't show me the source and target.  It wouldn't surprise me if I screwed up the connection, but a little more explicit feedback would be nice.

**Comment by merryman** [comment]
Yes indeed it looks like a botched connection. Usually happens when the target is undefined. I added some more information to display on the edit prompt to clarify what the source and target are.
