### ISSUE TITLE
Inspector doesn't show every member of an object

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#142]
I created this object with four fields, but the inspector only showed me three.  So I looked for the fourth object in the workspace, and sure enough, it's there.  See this screenshot.
![image](https://user-images.githubusercontent.com/656259/103359050-f65a4800-4a6b-11eb-954a-7a1935f1744b.png)

**Comment by merryman** [comment]
There is a convention that all properties prefixed with internal are hidden if the "Internals" box is not checked :-)
