### ISSUE TITLE
Whern the scene graph is open, text input is disabled

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#1429]
**Describe the bug**
When the left sidebar is open, on text entry, lively gets into a mode where text input is disabled, and doesn't re-enable until the user hits escape.  This happens to me in every editor that Lively has, and in text morphs.  In fact, in text morphs it is  always the case when I open up a new text morph.  And then I can't edit the text morph until I go back into edit mode and select the text morph.

I can appreciate that what's likely happening is the sidebar is grabbing the mouse events, and this may be difficult to fix.  But it's unexpected behavior (in fact, I had to experiment to find out that the sidebar was the culprit).  And if the user knows what's happening it's easy to workaround (just hit escape!).  So it may be that the best fix is just to indicate to the user on text morphs that editing is disabled (tooltip?  gray out the text?)

**To Reproduce**
Open up the **scene graph**, then open up a new text morph and start typing.  Nothing happens

**Screenshots**
No applicable screenshots (it would just be a sidebar and a blank text morph)

**Setup**
Please delete non-applicable items!

- Windows
- Linux

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).

acaf0fc025a77f874d9c036b7827cdcaf624afee

**Comment by merryman** [comment]
@linusha To clarify, @rickmcgeer means when the **Scene Graph**, not the properties panel. When you do that with the way described above, it indeed messes up the auto edit behavior after creating a text morph.
