### ISSUE TITLE
Frozen page is blank due to a bunch of failed links in the compiled page

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#1435]
**Describe the bug**
The latest version of Galyleo Dashboard Studio shows as a blank page, and when I look at the console I see a bunch of not-found error messages.  The compiled page is at:
https://storage.googleapis.com/user-galyleo-dashboards/test/studio-en/index.html

**To Reproduce**
The project is https://github.com/engageLively/galyleo-dashboard and the compiled page is built with the script build.sh in the root directory.  To see GalyleoDashboardStudio in the editor, execute `part(GalyleoDashboardStudio).openInWorld()`
```
$world.execCommand("open browser", {moduleName: "studio/ui.cp.js", packageName: "engageLively--galyleo-dashboard", codeEntity: "GalyleoDashboardStudio"});
```

**Screenshots**
The dashboard studio shows up in the editor like this:
![image](https://github.com/LivelyKernel/lively.next/assets/656259/2ecc3001-2c47-404e-b969-2de31e8414f4)

The compiled page is blank.
I can't really make sense of the console error messages and there are a lot of them, so perhaps it's best to try it yourself.

**Setup**
Please delete non-applicable items!

- Windows
- Linux

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).

**Comment by merryman** [comment]
Looking at the console log, the requested file URLs are exactly the way they are supposed to be. It appears this is more something with the way the storage bucket is configured. Maybe it just exposes the `index.html` and nothing else? You need to recursively make the entire folder and all its file public, not just the `index.html' itself.

**Comment by rickmcgeer** [comment]
I'm having the same issue with http://127.0.0.1:9011/local_projects/engageLively--galyleo-dashboard/bin/studio-en/index.html; in fact, I copied this to the storage bucket because I didn't want to force you to run build.sh to reproduce.

**Comment by rickmcgeer** [comment]
And I just looked at a few files at random and they are fine

**Comment by merryman** [comment]
Just checked whats going on with the build locally, the build scripts are severely outdated. I will prepare a PR for galyleo-dashboard that covers this.

**Comment by rickmcgeer** [comment]
Thanks!
