### ISSUE TITLE
Visible scrollbars on project display on dashboard

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#1444]
**Describe the Feature**
This isn't serious enough to call it a bug, but it is confusing to the user.  The scrollbars on the project display don't appear initially (see screenshot) which means there isn't any obvious way to navigate to the right project if it isn't in the top few displayed.  I am not sure if the scrollbar widget is configurable so that it always appears, but it's worth doing in this case if it is.

**Graphics**
![Screenshot 2024-04-27 111340](https://github.com/LivelyKernel/lively.next/assets/656259/b8602a69-7dc0-4b95-bf1c-c730b642cee5)

**Implementation Details**
Actually, while the images are attractive, when I'm trying to open a project ease of navigation is my first concern.  A simple text list, analogous to the Explorer in MacOS/File Explorer in Windows/File List in drive is more than adequate, especially if it's sortable by name/description/modified date/etc.  A search would also be nice...
I'd be happy to help implement it; I'll do a branch and PR if you can point me at the dashboard code, or, come to that, I can just do a Project Explorer component.

**Comment by linusha** [comment]
@rickmcgeer thanks for your feedback! I'll look into the scrollbars!

Regarding the pictures - yes, they are more or less placeholders right now. For worlds we had an actual picture preview generation. We'd like to have something similar for projects, but could not yet figure out what one should actually preview, as there is no real "state" inside of a project and one has more freedom with regards to what is actually the "main" component inside of a project.

Regarding the search: There is a search in the top right corner. Does it not work for you? Or is it just hard to find? It searches for name, description and metadata.
![image](https://github.com/LivelyKernel/lively.next/assets/14252419/327f6469-ad65-4a27-a5cf-bf4763a6f172)
