### ISSUE TITLE
List label should update when the list items change

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#145]
This is common with every other list, but in Lively the user has to make a selection to change the label even after the items are updated.  See the screenshot.  I tried a workaround (list.items = [...]; list.selection = [...][0] but then nonzero items weren't selectable.

![image](https://user-images.githubusercontent.com/656259/103413349-f7ec4480-4b2d-11eb-938a-f2400ad4d3e6.png)

**Comment by merryman** [comment]
Sounds reasonable to me! Will add asap.

**Comment by merryman** [comment]
Added in: ec8422c
