### ISSUE TITLE
Unhelpful error message

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#1458]
**Describe the Feature**
When a fontName in my project is invalid, I'd like to know what the invalid font is!  I spent a morning chasing this one down.  The bad font was Barlow, but all I saw was an error message saying 'Invalid Font Name!'.  Great.  What was it, how do I fix it?
The code that threw the error is in:
```
$world.execCommand("open browser", {moduleName: "text/morph.js", packageName: "lively.morphic", codeEntity: "fontFamily"});
```
The specific code is: 
```
if (!availableFonts().map(f => sanitizeFont(f.name)).includes(sanitizeFont(fontFamily))) {
            $world.logError('Invalid Font Name!');
          }
```

**Implementation Details**
Just change the line to 
```
$world.logError(`Invalid Font Name ${f.name}`);
```

**Comment by linusha** [comment]
Absolutely right, I'll fix this! Thanks for the input!
