### ISSUE TITLE
Build scripts should clean previous builds

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#1467]
**Describe the Feature**
I just got bit by this -- I fixed a bug that only showed up in the built application, re-built and the bug was still there!  When I looked in the console, the code hadn't changed, and when I looked in the bin directory there were multiple versions of the application with different dates.  No problem, I just cleaned the directory and rebuilt, but this really did feel like a trap for the unwary that's going to bite someone some day

**Graphics**
If applicable, provide screenshots/videos of similar ideas in other software.

**Implementation Details**
Just put `rm -rf <build directory>/*` as the first line of the build script.

**Comment by linusha** [comment]
Recent versions of lively projects come with the following script target in the package json: `build: "rm -rf build/* && export MINIFY='' && ./tools/build.sh"`, meaning that `npm run build` will always do exactly as you propose. 

I just checked and indeed the `galyleo-dashboard` project does not do this, but as you run highly customized build script anyways, you should probably just add them yourself.
