### ISSUE TITLE
It's too easy to push the update button when you're trying to copy the version

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#1488]
**Describe the bug**
I ran into this just now; I was trying to grab the version for an issue report, and I accidentally hit the "update" button, which means I can't get the version since it's updating

**Setup**
Please delete non-applicable items!

- Windows
- Linux

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).
af0c3623fbe24a48097cb69eace75feafddf0406v
I got the version from git log, since Lively is still updating...:-(

**Comment by linusha** [comment]
Oh damn yes, this is infuriating. Thanks for reporting this. I'll fix it.
