### ISSUE TITLE
Pressing "Open" on the Component Browser makes the Component appear _under_ the browser window

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#1489]
**Describe the bug**
Clicking on a component and then clicking "Open" instantiates the component -- right _under_ the component window!  And so from the naive user's perspective, nothing happens until the component window is moved.

**To Reproduce**
Instantiate the component browser, select a component, press open

**Screenshots**
![image](https://github.com/LivelyKernel/lively.next/assets/656259/bb19cb3a-4148-44f4-bcbc-d9c306c64ec2)

**Setup**

- Windows
- Linux

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).
af0c3623fbe24a48097cb69eace75feafddf0406

**Comment by merryman** [comment]
I can not really reproduce the issue with the component being opened below the component browser. It just happens to be when I re-select the window of the component browser. Then of course, the component browser is moved again to the front. Now I suspect for small components it is a little hard to catch them once they are opened. So I am fine with opening a halo on the opened component, to highlight the component more strongly.
