### ISSUE TITLE
Opening Mardown files in SystemBrowser causes parser crash

### ISSUE THREAD

**Issue by merryman** [LivelyKernel/lively.next#1512]
![broken-browser](https://github.com/LivelyKernel/lively.next/assets/1296388/d4b3f55a-9dad-4884-af57-1b5007756910)
It appears to be killing the parser:
![error log](https://github.com/LivelyKernel/lively.next/assets/1296388/94549b08-5d6c-41eb-b75f-7193e2f16ce1)

**Comment by linusha** [comment]
Huh, this will be due to the updated `CodeMirror` code. Does this happen with all markdown documents? I am just wondering as I was able to confirm that the syntax highlighting is now correct, meaning I could open at least one file :see

**Comment by merryman** [comment]
No, not all. It appears to be tirggered by a specific syntax that is more likely to appear in larger markdown files. Hence I mostly observe the issue opening larger markdown files.
