### ISSUE TITLE
Properties Panel is weirdly layouted after a few selection 

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#1537]
Should look like this:

![Screenshot from 2024-05-22 21-27-27](https://github.com/LivelyKernel/lively.next/assets/14252419/9385e9ae-c42d-405c-80a8-49dfa642431b)

After selecting a few morphs looks like this:

![Screenshot from 2024-05-22 21-27-54](https://github.com/LivelyKernel/lively.next/assets/14252419/c7d44653-9294-4dd7-adba-7a782d22c55a)

**Comment by merryman** [comment]
Lets review if this is still present after the layout updates have been merged.

**Comment by linusha** [comment]
Has been fixed with #1551.
