### ISSUE TITLE
World reloaded with morph opacity = 0

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#156]
See the attached screenshot.  All three submorphs of dashboard were invisible.  A little detective work showed that the opacity had been set to 0.  Component issue?

![image](https://user-images.githubusercontent.com/656259/104126414-3beefe80-5311-11eb-8937-ee7c59ade9f3.png)

**Comment by rickmcgeer** [comment]
Moreover, mousing over the components after opacity set to 1 resets the opacity to 0

**Comment by merryman** [comment]
This happens because master components can not be found. Related to #157
