### ISSUE TITLE
World reloaded with components screwed up

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#157]
This seems to be related to issue #156.  Briefly, the Filters are completely screwed up.  When I mouse over them, they disappear; I can't select them except in the Scene Graph sidebar, and when I select them there the Styling Palette nothing shows up -- the Styling Palette doesn't update.  As for the filters themselves, they are a mess, as these screenshots show:
![image](https://user-images.githubusercontent.com/656259/104126750-2f6ba580-5313-11eb-844a-1113979caf48.png)
![image](https://user-images.githubusercontent.com/656259/104126796-70fc5080-5313-11eb-9883-2629126a2441.png)
![image](https://user-images.githubusercontent.com/656259/104126823-ab65ed80-5313-11eb-8617-3d3b3338b5f0.png)

**Comment by rickmcgeer** [comment]
Well, this is a partial explanation: almost all components have disappeared!  (I hope they can be recovered!)
![image](https://user-images.githubusercontent.com/656259/104126917-16172900-5314-11eb-9b38-01d8bbbc4035.png)

**Comment by rickmcgeer** [comment]
And I can't revert to previous versions!  When I try, and either click Revert or Visit, I see a spinning wheel and loading message for a while and nothing happens.

**Comment by merryman** [comment]
Yes, this was a grave mistake from my side. Will be fixed soon!

**Comment by merryman** [comment]
Fixed now in: ec047d6. There is a pending issue with text morphs that suffer from a messed up bounds computation due to latent setting of the fixedWidth/Height properties via master component. Will fix that.
