### ISSUE TITLE
Strange Behavior in SelectableEntryMorph

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#1578]
**What would you like to achieve?**
This isn't a bug in Lively, but it's mystifying to me and I hope that @merryman can help.   This is the underlying cause of https://github.com/engageLively/galyleo-dashboard/issues/198.  Briefly, in any of the selectable lists in Galyleo, when an item is deselected it disappears from the list!  We haven't changed our code, so something happened in Lively that we aren't tracking.
Briefly, all of these lists have show two icons to the left of each list item: either three bars (when in orderMode), to indicate grab and move, or  a checkbox (when in editMode), to indicate select/deselect.  See:
![image](https://github.com/LivelyKernel/lively.next/assets/656259/9894f9fe-a076-4518-a894-1b36da069d8d)

Now the problems that I'm having are:

- Both the grab bar and the select checkbox are showing at the same time
- When an item is deselected, it disappears from the list
- The grab bar is completely non-functional
- When the "select all" button at the top left of the list is hit, all of the items on the list disappear
- The pen button, to toggle orderMode and editMode, is non-functional

As I said, this is very new behavior.

The List Morph code is here: `$world.execCommand("open browser", {moduleName: "studio/shared.cp.js", packageName: "engageLively--galyleo-dashboard", codeEntity: "GalyleoListMorph"});`

The SelectableEntryMorph code is here: 
```
$world.execCommand("open browser", {moduleName: "studio/shared.cp.js", packageName: "engageLively--galyleo-dashboard", codeEntity: "SelectableEntryModel"});
```
I've noticed a few things:

1. The bindings for the mouse actions don't have a target
```
bindings: {
        get () {
          return [
            { signal: 'onMouseUp', handler: 'toggleSelect' },
            { signal: 'onDrag', handler: 'onDrag', override: true },
            { signal: 'onDragStart', handler: 'onDragStart', override: true },
            { signal: 'onDragEnd', handler: 'onDragEnd', override: true }
          ];
        }
      }
```
2. `orderMode` and `editMode` are properties with `defaultValue`, but they are never directly set
3. The bug appears to be in `SelectableEntrryMorph.onRefresh()` but I am having trouble tracking it

Any thoughts?

**How are you trying to achieve that**

**Alternative solutions**
If applicable, what other solutions have you tried?

**Additional Resources**
Please provide links to any custom code that might be necessary to grasp your problem. Screenshots of custom component, etc. are also appreciated. 

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).

**Comment by merryman** [comment]
This is really more of a ticket for the EngageLively Repository. Overall the issue here is that you are resetting masters continuously in the code instead of using component states. That leads to several weird behaviors. I will prepare a PR for this on the project repository.
