### ISSUE TITLE
Lively needs a dock...

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#1581]
**Describe the Feature**
Window management is a big issue when I am using Lively, particularly  windows for Browsers, Editors, and Inspectors that don't show up in the screen graph.  Because they don't show in the screen graph, there's no way to easily locate them when they're hidden.  Moreover, when they're collapsed, the location of the remaining titlebar is picked (from a user's perspective) essentially at random.
My screen, right now, looks like this...
![image](https://github.com/LivelyKernel/lively.next/assets/656259/c52195ed-b88e-4e34-a345-a0389796bc3c)

**Graphics**
Docks are ubiqutous.  Of course, the most famous example is the dock in Windows and OS/X:
![image](https://github.com/LivelyKernel/lively.next/assets/656259/15f4c4bb-c6a5-4dd2-b1f4-4e83a344d51e)
But mini versions are the editor tabs in VSCode:
![image](https://github.com/LivelyKernel/lively.next/assets/656259/ae51064e-dcfb-422d-af77-d0ab129b3dbb)

**Implementation Details**
If applicable, provide insights with regards to implementing this feature that you already have.
My suggestion would be a flap on the bottom of the editor, similar to the screen graph sidebar flap.  The version widget could go there, too.  To save screen real estate it could be made retractable, like the screen graph side flap is, now.  I assume this would either just directly use
`$world.execCommand("open browser", {moduleName: "studio/flap.cp.js", packageName: "lively.ide", codeEntity: "extent"});` or would have a new view/Model pair which is similar.  The layout itself is really simple.
A second idea (simpler to implement, and maybe cleaner) is just to have a second list in the scene graph sidebar,  for the meta-objects.  This should actually be really easy, since the Properties Panel sidebar has a bunch of different kinds of items in it.

And, yes, I'll be happy to work on it.

**Comment by merryman** [comment]
@rickmcgeer Do you know about the [Window Switcher](#670)?

**Comment by rickmcgeer** [comment]
I didn't, and thanks.

**Comment by rickmcgeer** [comment]
Ah, found "Window switcher" on World Menu!
