### ISSUE TITLE
Open editor on object from its inspector (or, more generally, from any workspace)

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#1582]
**Describe the Feature**
When I'm inspecting an object, I often want to look at the code as well as the inspection.  However, the inspector is a different window -- what I'll typically have to do is find the object again, click on the wrench icon, and pop open an object editor.  Which is obviously a slightly inconvenient workflow.

**Graphics**
Lively still does this better than anyone, so no competing screenshots.

**Implementation Details**
Honestly, 90% of the cases are covered by an edit method I can just evaluate, e.g., `this.foo.edit()`.  Or a keyboard shortcut (<ctrl>-Shift-E, for example).
Actually, now that I think about it, maybe a combined Editor/Inspector would be more convenient.

**Comment by merryman** [comment]
Does this help? 

![object editor from inspector](https://github.com/LivelyKernel/lively.next/assets/1296388/d5195d25-e537-4fd8-8381-ebb100217aec)

I realize that for some reason the keyboard shortcut does not work. I will look intro it.

**Comment by rickmcgeer** [comment]
It does!  It took me a little while to figure out that "editIt" went to the selection.  When I initially tried I got the "No target for ObjectEditor" message.
This works fine!  One suggestion is that if there is no selection, the target for the OE should be `this`
