### ISSUE TITLE
Can't load Object Editor

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#16]
![image](https://user-images.githubusercontent.com/656259/96305975-9ea35900-0fb3-11eb-9e17-3ed0ca93751b.png)

**Comment by merryman** [comment]
Can this be reproduced in a slow loaded world?

**Comment by rickmcgeer** [comment]
I tried a slow-loaded world and got another issue.  See issue #18

**Comment by merryman** [comment]
Should be fixed now.
