### ISSUE TITLE
Incorrect article

### ISSUE THREAD

**Issue by frcroth** [LivelyKernel/lively.next#160]
When a morph is created without a name, its name is "a"/"an" classname. The distinction between a and an is performed based on whether the word starts with a vowel. Unfortunately this is not correct, as this is not the general rule in English. For example "Uniform" is written with a vowel, but the correct article is "a".
The `articlize` method from `articles` (https://jspm.dev/npm:articles@0.2.2!cjs) can do this.

**Comment by merryman** [comment]
Sounds like a nice improvement. Can you prepare a PR that suggests a fix?

**Comment by frcroth** [comment]
> Sounds like a nice improvement. Can you prepare a PR that suggests a fix?

See #189

**Comment by frcroth** [comment]
Closed with #189
