### ISSUE TITLE
`withAllSubmorphsDo` and related methods 

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#161]
This is just something I fell over pretty hard a few days ago:

1. `withAllSubmorphsDo()` and the other related methods (detect,...) do not only traverse the submorph-hierarchy but start with the morph they were called on itself. This was not obvious to me from the name alone.
This might just be my bad however? In any case it should probably not be changed.
However, it might be nice to have corresponding methods that do not start with the morph they are called on but only traverse the submorph hierarchy? Something like `withoutSelfWithAllSubmorphsDo()`.

2.  The aforementioned methods all traverse the complete hierarchy downwards. This might be a bit squeak-esque, since it can also be done with `forEach()` easily, but we could provide a function that only iterates over the submorphs of the morph it has been called on and not deeper, just to make the code more expressive. Something along the lines of `withAllDirectSubmorphsDo()`.

Let me know what you think, I can provide implementations including tests if you think this is worthwhile to have.

**Comment by merryman** [comment]
1. I would prefer to add an additional argument or different way of configuring `withAllSubmorphsDo()`instead of introducing a new function. It just seems like too minute of a change for my taste.
2. There is `withAllSubmorphsDoExcluding()`, where you can filter out specific morph which will not be traversed further:
```
m.withAllSubmorphsDoExcluding(each => {}, each => each.owner != m);
```
