### ISSUE TITLE
Drop-down buttons resize when items are chosen

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#164]
Which of course screws up the layout when it's reliant on a drop-down being a specific size.  A drop-down should be a fixed size.  Lists are, independent of the size of the selection.

**Comment by merryman** [comment]
Yes this is a behaviour that is inherited down from buttons. But to be hones, I am not sure to what extend we ever want to autofit buttons. Thoughts anyone?

**Comment by merryman** [comment]
As of now (5e59f1fd1e9962c2c14c8f9810d73726fcff5ab9) this behavior is not longer in the system since we have outsourced the wrapping and layouting of buttons entirely to the layouts.
