### ISSUE TITLE
Pulldown menus are different from drop-downs

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#165]
And both are needed.  I may be using the wrong terminology here.  What I mean by a pulldown are the menus for almost every application on a Mac or PC, at the top-left corner.  These invoke actions but typically don't set persistent state, and visually are shown by titles.  A dropdown is what we have; its function is similar to a bunch of radio buttons.  It offers a single choice, changes state, and its current value is shown on the label.
In Lively today, drop-downs are used for both.

**Comment by merryman** [comment]
In fact this one can be implemented quite easily by creating a custom button that just uses `$world.openMenu()` accordingly.

**Comment by merryman** [comment]
@rickmcgeer do you want us to provide a more user friendly way to add these menu buttons? The main challenge I see here is like what I already encountered when creating “user friendly tree views”. While you can come up with a straight forward input for hard coded menu items/tree views, it is difficult to make them dynamic i.e. respond to different context, define action handlers etc.

**Comment by linusha** [comment]
Closed as stale for now.
