### ISSUE TITLE
Lively2Lively Client getting dropped silently from rooms

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#166]
I had an L2L client in testRoom1 that wasn't getting any messages.  When I tried await client.joinedRooms(), testRoom1 showed up on the list.  When I tried client.joinRoom('testRoom1'), it failed, so it clearly thought it was in the room.  However, no messages were being received.  So I tried client.leaveRoom('testRoom1') and then client.joinRoom('testRoom1'), and messages came in.
So I conclude that the server had dropped the connection and simply not told the client.  There should be some way for the client to check its status.

**Comment by rickmcgeer** [comment]
As I think about this, this has to be an issue with rooms rather than the tracker.  I can still connect to L2L just fine, and in fact I am querying the rooms from L2L.  So clients must be kicked out of rooms at some interval.  This should just not be done silently.

**Comment by rickmcgeer** [comment]
I isolated the problem.  It happens on a save.  Another world continued to receive messages reliably for days.  So I tested; re-initialized the client, sent a bunch of messages, saw they were received.  Saved the world, messages stopped coming.  Re-initialized, everything works.

**Comment by merryman** [comment]
@rickmcgeer Am I right that this also is not really a bug in l2l but instead some issue with duplicate initializations of l2l clients due to dangling connections and hidden morphs?

**Comment by merryman** [comment]
@rickmcgeer can this be closed now?

**Comment by linusha** [comment]
Closing this as stale.
