### ISSUE TITLE
Lively2Lively client needs to addServices TWICE before it processes messages

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#167]
My initClient() routine had an addServices() call, and I checked that it had loaded by checking
this.client.actions['[el-jupyter] message'].  Nonetheless, it wasn't processing messages.  When I added a console.log('foo!') message and reloaded, it worked.  Of course the console message could have nothing to do with it, so I tried a second call to this.client.addServices(this.services) and that worked fine.
The world is https://matt.engagelively.com/worlds/load?name=Dashboard%20Studio%20Four
This is probably what was going on with Issue #166

**Comment by rickmcgeer** [comment]
Further experimentation shows that a delay is needed between the first and second addition of services.  Specifically, I added a second call to this.client.addServices() after joinRoom(), and this had no effect.  But if I then waited several minutes and made another call to this.client.addServices(), it started receiving messages.

**Comment by rickmcgeer** [comment]
I tried looking at this in the debugger, and it behaves very differently.  In the debugger, I get a timeout, but the callback IS executed...

**Comment by rickmcgeer** [comment]
To say this is bizarre is the understatement of the year.  At the end of onLoad(), I put in a call:
setTimeout(_ => this.client.addServices(this.services), 10000);
This was the second call to this.client.addServices, and  10 seconds is plenty of time to wait.  Didn't work.  Then I ran it manually, and after that messages were received just fine.

**Comment by rickmcgeer** [comment]
OK, it's definitely running the thing manually that works. 
setTimeout(_ => this.client.addServices(this.services), 300000);
didn't work

**Comment by rickmcgeer** [comment]
Running this.client.addServices(this.services) manually always works; invoking it from code never does.

**Comment by rickmcgeer** [comment]
My next guess is that it was a naming thing.  So I tried renaming this.client to this.l2lClient and this.services to this.l2lDashboardServices.  No effect.  Running on initialization doesn't help, running manually does.

**Comment by rickmcgeer** [comment]
I wrapped this as:
__initServices__() {
  this.l2lClient.addServices(this.l2lDashboardServices);
}
Running this within the onLoad() suite had no effect, but running it by pressing the execute button on the bottom of the Object Editor got it to work.

**Comment by rickmcgeer** [comment]
Last comment for the night.   It turns out to be a bad binding of the instance variable this on load.  This was shown by putting the call console.log('hello') at the start of the callback, namely:
`get l2lDashboardServices () {
    const self = this;
    return {
      '[el-jupyter] message' (tracker, { sender, data }, ackFn, socket) {
        console.log('hello');
        self.lastMessageTime = new Date();
        self.__logEntry__('message Received from ' + sender);
        self.__lastPayload__ = data.payload;
        self.__addTableFromMessage__(data.payload);
      }
    };
  }`
the console.log('hello') executed, but nothing else showed up.  Which indicates that self was referring to something other than this.

**Comment by rickmcgeer** [comment]
And that was it.  `this` changed identity at some point.  I changed the call to console.log(`hello from ${self.id}$`), and what was printed on the console was: Dashboard_38190BA8_92C0_4FC2_9F71_257C73E3EC9B.  I then looked at dashboard.id in the inspector, and got: Dashboard_B0347CB1_6E44_49E1_BE0D_271CA75508D9.  So that's it.  Once loading was finished, the dashboard's id changed, and methods were executing in a different context.  
What I don't understand is how other L2L clients seem to work.

**Comment by rickmcgeer** [comment]
And, finally, the workaround: tell the method to resolve the reference at runtime, using db = $world.get('dashboard');.  This is obviously not a universal solution but it lets me proceed for awhile while we work out the conflict that led to this bug.

**Comment by merryman** [comment]
I will close this now, it seem it was not related to l2l after all.
