### ISSUE TITLE
Need to be able to access world menu when the world is full of submorphs

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#168]
A good example is https://staging.engagelively.com/edit/galyleo%20editor.  This editor wants to take up the whole world, and in fact has code to enforce this on move or resize.  But ATM, the only way to save the world is by right-clicking on a blank area of the screen or using a memorized keystroke.  The world menu should be accessible from the top bar.

**Comment by merryman** [comment]
#159 Contains a more beefed up top bar that allows to trigger world saves from there. That should alleviate things to some extent. But I will keep what you suggest in mind.

**Comment by merryman** [comment]
The top bar now allows to save the world. Can this be closed for now?
