### ISSUE TITLE
Components Browser doesn't work when Fast Load is enabled.

### ISSUE THREAD

**Issue by zarp-dev** [LivelyKernel/lively.next#169]
Components Browser doesn't work when Fast Load is enabled.
It's trying to load endlessly.
![Screenshot 2021-01-30 at 21 05 29](https://user-images.githubusercontent.com/65812041/106364299-069d6580-633f-11eb-96aa-833dbea5a335.png)

**Comment by merryman** [comment]
Thank you, should be fixed now in: ec88301
