### ISSUE TITLE
Way too many choices for Color when I try to fix undeclared vars!

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#17]
![image](https://user-images.githubusercontent.com/656259/96339657-f345e300-104a-11eb-8e9d-096c7e24f735.png)

**Comment by merryman** [comment]
This is actually an issue with the fast loaded worlds right now. I am gonna fix this in the future. But maybe once we speed up the slow loading, this wont be nesecary.

**Comment by linusha** [comment]
I just checked with `Color` inside of a JS workspace and this seems fixed. If I am mistaken, feel free to reopen!
