### ISSUE TITLE
Workspace output is too big.

### ISSUE THREAD

**Issue by zarp-dev** [LivelyKernel/lively.next#170]
Workspace output is too big. It should be smaller.
![Screenshot 2021-01-30 at 22 24 30](https://user-images.githubusercontent.com/65812041/106366012-369e3600-634a-11eb-87ea-2b82fd515403.png)

**Comment by merryman** [comment]
Yes, this is due to a messed up state of the message morphs. When I find time, I will revise them. Thank you!

**Comment by NikolaySuslov** [comment]
@zarp-dev As a quick fix, you could override StatusMessage #fit method in  StatusMessageForMorph (lively.halos/markers.js), so that it will aware on all submorphs, not only 'message text' submorph.
```
fit () {
    const minHeight = 35; const minWidth = 100;
    this.extent = pt(minWidth, minHeight).maxPt(this.globalBounds().extent());
    this.relayout();
  }
```

**Comment by linusha** [comment]
This should be fixed with the new text rendering.
