### ISSUE TITLE
When the top bar is in place, world (0,0) should be at the bottom of the top bar

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#171]
Either that, or the top bar should be retractable.  I can figure it out, but, still, sheesh.

![image](https://user-images.githubusercontent.com/656259/106371543-646b8680-631a-11eb-95e5-a3fc5aaad4ac.png)

**Comment by linusha** [comment]
`visibleBoundsExcludingTopBar()` on the world was added a while ago. I introduced it for maximizing windows respecting the topbar. Does this suit your needs?

**Comment by rickmcgeer** [comment]
Probably, and thanks.  It's @merryman's code that I am modifying, but this sounds like it will do the trick.  Thanks!
