### ISSUE TITLE
Incorrect behavior of the "Change DB" button.

### ISSUE THREAD

**Issue by zarp-dev** [LivelyKernel/lively.next#172]
I tried to save my world and clicked the "Change DB" button, after which I got the following:
![Screenshot 2021-02-01 at 13 16 30](https://user-images.githubusercontent.com/65812041/106445337-f1841c00-648f-11eb-95fb-6321e886e1a4.png)

**Comment by merryman** [comment]
I was planning of removing this button for the time being, since I do not have time to go over the morphic-db tools for the foreseeable future. I am curious though, did you have a particular use case in mind? If so, I put that back on my todo list.

**Comment by linusha** [comment]
The button has been disabled.
