### ISSUE TITLE
Halos get misaligned with morphs (after window scrolling, I think)

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#173]
I've used the fix @linusha suggested for the top bar, and this may have something to do with it...
![image](https://user-images.githubusercontent.com/656259/106525767-5abc5d00-6499-11eb-936d-66b792bfe5a0.png)

**Comment by merryman** [comment]
No this is because you have manually set the position of the world to be offset from 0,0 which messes with the bounds computation of the halos.
