### ISSUE TITLE
Potential label resizing on font change

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#176]
In the Date Picker, I wanted each date to be fixed-width so that clicking on the label square would work, so I changed the font family to IBM Plex Mono.  Then, clicking stopped working on any square with two digits in it (I used an onMouseDown method), and when I checked:
this.submorphs.map(m => m.extent) 
I saw that every double-digit square had size pt(0, 15).  
this.submorphs.forEach(m=>m.extent = pt(15,15)) 
solved it, but I don't know how the squares got resized so I thought I would ticket it.

**Comment by rickmcgeer** [comment]
This is happening every time I change month, in other words, every time I reset the textstring of the labels.  For a workaround I will simply hardcode the resize into the update function.
The world is https://matt.engagelively.com/worlds/load?name=Sliders

**Comment by rickmcgeer** [comment]
Setting autofit = false for each date fixed the problem.   So there is nothing to be fixed, but when autofit = true the size was getting set to (0,15) on each redraw

**Comment by rickmcgeer** [comment]
The last comment was wrong; even with autofit = false I'm seeing the problem.  For the moment, I just rest the morph size explicitly on each assignDates(), but this is something that (at least) we need to discuss

**Comment by merryman** [comment]
For the record: This was because @rickmcgeer used`Label` instead of `Text`. As labels will not support fixed width, he ran into the problems above. Now I will close this, but we should think about unifying labels and text morphs. There is no reason to expose implementation details through the morphic API.
