### ISSUE TITLE
onMouseOver changes the label on a dropdown list back to '1'

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#179]
This is what it shows originally
![Screen Shot 2021-02-14 at 17 04 59](https://user-images.githubusercontent.com/656259/107895079-e21cbe00-6ee6-11eb-9953-6ac8e84f4c02.png)
This is after selection
![Screen Shot 2021-02-14 at 17 05 10](https://user-images.githubusercontent.com/656259/107895097-f5c82480-6ee6-11eb-9531-39dfb1ed10d5.png)
And this is after mouseover
![Screen Shot 2021-02-14 at 17 05 16](https://user-images.githubusercontent.com/656259/107895118-024c7d00-6ee7-11eb-988e-e24ccdca33a7.png)

**Comment by merryman** [comment]
Thank you! This was actually a bug in the change manager that screwed up the whole system once it got derailed. Fixed in: 9e34c889
