### ISSUE TITLE
Unexpected behaviour when initializing `grabbable` via defaultValue

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#182]
We initialized a Morph to be `grabbable` in it's props via `defaultValue`. However, this did not have the desired effect, since this did not also lead to `draggable` being set as well.

Setting `grabbable` explicitly via code solved this, since `draggable` gets set in the setter too. However, this setter seems to not be used when initializing via `defaultValue`.

**Comment by merryman** [comment]
Yes the defaultValue does NOT trigger the setter. You would need to instrument both grabbable and draggable with defaultValues to achieve what you want with just defaultValues.

**Comment by merryman** [comment]
Closing this now, since I assume the question was answered.
