### ISSUE TITLE
Dashboard Preview screen should show full project name

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#185]
This looks very nice, but what I need is the full project name....
![image](https://user-images.githubusercontent.com/656259/108545547-c88bc580-729c-11eb-85d3-20baef615baa.png)

**Comment by merryman** [comment]
Right now, the correct world can still be found by entering the full proper name in the search field, but this is indeed a problem. I would say a automatic slide animation on hover could solve things?

**Comment by merryman** [comment]
Fixed now. We have a rolling view of the name if it exceeds the tile bounds.
