### ISSUE TITLE
Import of base classes

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#19]
Constantly importing point and Color was a pain in the neck in engageLively -- in lively.next the plethora of classes makes it impossible (see issue #17).  This could be in a per-user config.json file, but I really think that pre-loaded classes are a good idea.

**Comment by merryman** [comment]
I think you are referring to having basic classes be imported in the workspace or the inspector. I don’t think this makes much sense when working with objects or modules. Yes, I will add a configuration in lively.morphic/config.ja that should allow these classes to be preloaded. This can then be overridden by the localconfig.js. I will provide a user friendly UI for configuring these options in the future too.

**Comment by JensLincke** [comment]
The fix imports is nice, but having to do this for even pt etc. is very tedious when you just want to type something in the inspector or workspace. (In Lively4 I use a development layer that provides such modules/classes... but filling the imports with some reasonable defaults would be nice)

**Comment by linusha** [comment]
This has been available for inspectors for a while now.
