### ISSUE TITLE
NumberWidget layouting breaks on copy/ serialization

### ISSUE THREAD

**Issue by frcroth** [LivelyKernel/lively.next#190]
As seen in the Video, a NumberWidget breaks a little when copied (the arrow buttons are moved). The copy is fine.

https://user-images.githubusercontent.com/6863832/108876349-6c0f0a00-75fe-11eb-8003-705d5b5ef7b5.mp4

**Comment by merryman** [comment]
I have seen this bug recently in different places. It seems to be because the labels (that are the arrow buttons) spontaneously resize on copy.

**Comment by merryman** [comment]
Should be fixed now in: aae525e3d74ac0a81febb8dfaf727a537d5bfc98
