### ISSUE TITLE
Scrollbars on lists and windows are hard to use

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#198]
1. On a window, the mouse icon goes immediately from edit to horizontal resize; there's a very small horizontal area (and it's on the inside of the scrollbar) where the mouse icon goes to arrow for scroll;
2. On a list, clicking on the scrollbar selects the item next to it on the list.

**Comment by merryman** [comment]
On thing we can do is bite the bullet and get to implement custom scrollbars. I have already done that in the past and it works quite well at least on desktop.

**Comment by merryman** [comment]
This has been fixed now: 7436f9c1
