### ISSUE TITLE
Editor overwriting good code

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#199]
On the entrance to methods, I often check to see if there is nothing to do, and if there isn't, return immediately.  So I often write code of the form:
if (nothing to do) {
  return;
}
do stuff;
This involves simpler conditions and less indentation than the equivalent:
if (something to do) {
  do stuff;
}
and less indentation than:
if (nothing to do) {
} else {
  do stuff;
}
But the editor helpfully knocks this out:
![image](https://user-images.githubusercontent.com/656259/110257769-1f0f2a00-7f54-11eb-8432-4cb205ebb681.png)
![image](https://user-images.githubusercontent.com/656259/110257802-436b0680-7f54-11eb-8750-c0c08ab08e7f.png)

**Comment by merryman** [comment]
This is done by our auto lint mechanism. We can either turn this return removal off or think about a manual triggering of the linter instead.

**Comment by merryman** [comment]
@rickmcgeer I can make the linter ignore empty returns by default. That would have solved this particular case. If you are fine with the state as is, I will close this one here though.
