### ISSUE TITLE
Python && lively.next ide

### ISSUE THREAD

**Issue by wwj718** [LivelyKernel/lively.next#2]
Hi，
I want to try Python with lively ide:

*  [lively.ide/py](https://github.com/LivelyKernel/lively.next/tree/master/lively.ide/py)
*  [lively.py](https://github.com/LivelyKernel/lively.py)

I don't know how to do, any guide？

Thanks

**Comment by merryman** [comment]
@wwj718 in case you figured out how to do it by now, feel free to add to the wiki. I can give you access. Aside from that, can this be closed?

**Comment by linusha** [comment]
https://wwj718.github.io/post/%E7%BC%96%E7%A8%8B/dan-ingalls-and-lively/
