### ISSUE TITLE
Extent overridden on copy

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#205]
I made a small copy of a button as a master component to be a close button, but whenever I instantiate it inside another master it resizes to the extent of button
![image](https://user-images.githubusercontent.com/656259/111315562-bb55c280-861f-11eb-8a70-2a520b9bce41.png)

**Comment by merryman** [comment]
@rickmcgeer Can you remember if this issue was due to duplicate names in the components?

**Comment by merryman** [comment]
I believe this may have been due to an incorrect padding assigned to the master component? The padding of a button is a higher level property, that is enforced on the morphic level. That may have been causing these inconclusive behaviors. Can you confirm @rickmcgeer ?

**Comment by linusha** [comment]
Not applicable anymore with new components.
