### ISSUE TITLE
Clear indexdb and local storage on world load?

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#21]
This is just an idea based on the fact that the workaround for some of the issues we've seen is to clear indexdb and local storage.  So one idea is to do this automatically on load; my assumption (which may be wrong) is that all this does for us is improve performance, and remember Ousterhout's Law: "90% of performance improvement is getting a working system".  Let's make the system robust and bug-free, _then_ improve performance.

**Comment by merryman** [comment]
Well, we use indexdb are used for caching, so clearing them by default on load will slow down the loading process tremendously. I would suggest an easily accessible button that allows the user to clear local storage.
For the future, where we have a larger number of people using lively, we can also let the server set a flag in the clients that triggers a reset of local storage after a rolling update (once).
Open for other suggestions.

**Comment by merryman** [comment]
So I found there is already a mechanism that enables that, I just forgot to update it. Should be fixed now in d38a05c5cb5dbb02b6a6a4d94eb11dc530a18237
