### ISSUE TITLE
Make the title bar and halos modal

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#216]
@merryman suggested posting this to lively.next, because a general discussion is needed on the right way to do this.  The title bar contains some items that are useful for an end-user and some that aren't, and, for that matter, some that are appropriate for some end-users and some that aren't.  Similar comments re the halo; copy, resize, delete, move are useful for end-users, and composition (grab/drop) are only useful with training (people are used to Group, but not this; grab/drop is better than Group, but unfamiliar...Finally, sometimes you want these tools enabled and sometimes not.  For example, in a Dashboard, in edit mode you want most tools enabled but when not editing, the only things movable should be the movable parts on widgets (e.g., a knob on sliders).  
So the question is, how do we make these tools modal, so they can be left on sometimes and turned off others?
And how do we make available restricted forms of tools?  For example, end-users will want to inspect (and modify) some properties of an object (typically those in the Styling Palette) but not others.

**Comment by merryman** [comment]
I have decoupled the top bar from the world and made it universally attachable to any kind of morph that is supposed to serve as an alternative "world canvas". See: 35b7b9d61e25ef0ed8a1a99cb204979b0cde57f8 I will soon post an example.
