### ISSUE TITLE
Fix CI build

### ISSUE THREAD

**Issue by merryman** [LivelyKernel/lively.next#219]
Our CI build has been broken for ages now and I think in the interest of improving the stability of lively.next we should tackle this issue rather sooner than later.

To recap: The main reason for this is, that a bunch of tests do not work outside of a browser any more and we are forced to run these tests in a lively.headless session (read: puppeteer) on the CI server. This has not been done yet.

An approach previously outlined by @linusha and which we discussed informally, is to transition the CI test to a node.js script that can be run from the console where all it does it fire up a l2l client which then talks to a headless lively session and runs + monitors all the tests in the session, printing the results to the console.
From my perspective this sounds like the right thing to do. The only obstacle so far being, that there is not bundled version for l2l that works in the browser.
An easy way to steer around that problem popped up in my mind recently. Looking at the startup script of the lively server, one can get an idea of how we bootstrap the lively module system within node.js: 
https://github.com/LivelyKernel/lively.next/blob/master/lively.server/index.js

Once bootstrapped it should be straight forward to run `System.import('lively.2lively/client.js')` and get the whole thing started as outlined above. Its basically just the server bootstrap script without the webserver stuff.

I dont know when I will have time to take a stab at this wo I am assigning to you guys @m-hemmings and @linusha in case you feel like it.

**Comment by merryman** [comment]
We should also use that as a chance to move over to github actions and move away from Travis.

**Comment by linusha** [comment]
Closed with eb6cb129656e3e324b267b8fe3b3f29fa620439f
