### ISSUE TITLE
Morphs Not showing up on Scene Graph

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#229]
This is in Dashboard Studio Development on https://matt.engageLively.com.  "user flap" is a submorph of "title bar", confirmed both by successive cmd-clicks to bring up halos and by running `this.submorphs.map(m => m.name)` on title bar.  But it's not showing in the scene graph:
![image](https://user-images.githubusercontent.com/656259/112707402-4d539b80-8e68-11eb-9995-51a856bafb8b.png)

**Comment by merryman** [comment]
That is actually a feature. User flap is part of lively.user package, which is right now excluded from the scene graph. The idea is that in general we are not interested in having IDE tools showing up in the scene graph. But maybe we should not do this via package but more via flag or so.

**Comment by merryman** [comment]
I will close this now, since that is now answered.
