### ISSUE TITLE
Cancel button at open workspace doesn't work

### ISSUE THREAD

**Issue by SilvanVerhoeven** [LivelyKernel/lively.next#23]
The cancel button in the window "open window" (Ctrl+K) doesn't close the window.

**Comment by SilvanVerhoeven** [comment]
Edit: Only sometimes, not reproduceable...

**Comment by merryman** [comment]
Could not reproduce either. Let me know if you catch it again!

**Comment by merryman** [comment]
@SilvanVerhoeven is this a thing still? If not I will be closing this.

**Comment by linusha** [comment]
Not reproducible anymore.
