### ISSUE TITLE
Components lose styling on copy between worlds

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#231]
Here's the morph as designed in the original world:
![image](https://user-images.githubusercontent.com/656259/112727040-b9241b80-8edd-11eb-808e-1958bfdac03c.png)
And here's the pasted version in the new world:

1. Font color and size on the placeholder have changed (from 17-pt, 204, 204, 204, to 12-pt black
2. Styling has been lost on the green and red buttons
![image](https://user-images.githubusercontent.com/656259/112727118-2041d000-8ede-11eb-9b8d-33d40eeeb7b8.png)

**Comment by merryman** [comment]
Now fixed in 8438430bcacfc1bf9b0f802fd61ba179e7b7da01
