### ISSUE TITLE
Undo of move on multiple morphs does not work

### ISSUE THREAD

**Issue by frcroth** [LivelyKernel/lively.next#233]
1. Create multiple morphs
2. Select them
3. Move them together, via halo
4. Try to undo

--> The morphs will disappear but not move back

https://user-images.githubusercontent.com/6863832/112858565-48822800-90b2-11eb-91c9-45ec34fabd15.mp4

**Comment by merryman** [comment]
Undo is generally broken in morphic. Anyone with time is welcome to take a stab at this :-)

**Comment by linusha** [comment]
Related to #104, closing here.
