### ISSUE TITLE
StatsWidget broken?

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#234]
I tried to add a stats widget from the component browser to my world. After it occurs in the world, as soon as my cursor enters it, it breaks. It becomes nearly invisible, only a frame with a shadow is there.

I tried another component (a dark number field) and that worked without problems.

**Comment by merryman** [comment]
Yes, I think this is something with html being considered a style properties of sorts. I will look into that.

**Comment by merryman** [comment]
This should be fixed now: 6f1cc53
