### ISSUE TITLE
Halo mode does not work as expected when a Morph other than the world is target of the topbar

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#236]
When attaching the topbar to a Morph other than the world and enabling halo mode by clicking the cursor in the topbar, clicking on a morph in the target does not trigger the halo of that morph.

I would have expected the same behavior as when doing this in the world, i.e. a halo opening.

**Comment by merryman** [comment]
Is this a duplicate of #237 ? Is so is that fixed now too?

**Comment by linusha** [comment]
I just tested it and is it fixed now. Thanks.
