### ISSUE TITLE
Topbarmode is not correctly set upon attaching a new target

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#237]
Steps to reproduce:

1. Choose rectangle mode in the topbar
2. Attach the topbar to another Morph
3. Now the rectangle mode will still be blue in the topbar, but the behavior will be that of the halo mode

Clicking the rectangle-mode button once again will lead to the expected behavior (the other expected option being that the mode of the topbar is correctly indicated visually). Therefore, this is only a visual problem.

**Comment by linusha** [comment]
I have not put a lot of time into understanding what the underlying problem is, but a call to `this.setEditMode(this.editMode)` at the end of `attachToTarget` solves this. Maybe this is helpful.

**Comment by merryman** [comment]
I think this can be closed for now?

**Comment by linusha** [comment]
@merryman I do not think this was fixed in the topbar itself, but I might have missed something?

I just remember that you said in the above PR (that was for another problem) that you could reproduce it. 

We just call the line mentioned above whenever we attach a target, which solves it for our project, but it might be worthwile to do it in the topbar? (Or find an even better fix, that one feels a bit sloppy).

**Comment by linusha** [comment]
@merryman I think this is fixed with 38a1d0f

**Comment by merryman** [comment]
It is indeed!
