### ISSUE TITLE
Versatile shortcuts for navigating tabs

### ISSUE THREAD

**Issue by SilvanVerhoeven** [LivelyKernel/lively.next#238]
Tab system: Introduce shortcuts to navigate between tabs, e.g. jump to right/left tab, jump to first tab etc.

**Comment by SilvanVerhoeven** [comment]
Just for "book keeping" reasons

**Comment by linusha** [comment]
As far as I am concerned, I would think this has been closed by a8eeb9bb55c63a5dc1b311983bafe0c5a702a763.
