### ISSUE TITLE
Text in ObjectEditor sometimes not reachable

### ISSUE THREAD

**Issue by SilvanVerhoeven** [LivelyKernel/lively.next#24]
Sometimes, some text in the ObjectEditor cannot be reached via Cursor. Hence, the text cannot be selected/edited.
The beginning of all lines is reachable, but one cannot go further right than a specific point. Selecting over several lines is possible, but only the text up to the certain point to the right is selected.

I cannot reproduce the error, but it happens from time to time during usage (sometimes right after opening the world, sometimes after longer working, but always after opening the ObjectEditor). The bug can be fixed by reopening the ObjectEditor.

**Comment by merryman** [comment]
This is a bug I encounter frequently, that lies somewhere in the text engine of morphic. What seems to be going on in particular is that the area that is not selected does not compute the proper character bounds. One thing you can do is to select the text with the inspector and toggle the “debug” property to true. It will show you the places that the text renderer knows the text bounds for. Somehow the logic seems to sometimes drop several lines. I have not yet gotten to figure out what is going on. You are welcome to dive into the problem if you have time and interest!

**Comment by merryman** [comment]
This should be fixed now in: 1bed90dd3fc04361d94579d083436230abc3cf15
