### ISSUE TITLE
Halos are persistent and only disappear when something else is clicked on the scene graph (matt.engageLively.com)

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#241]
![image](https://user-images.githubusercontent.com/656259/113794702-01beae80-9700-11eb-9eb1-b83dc9e0cb2c.png)

**Comment by merryman** [comment]
Try clearing your cache, I cant reproduce this on any browser and neither in icognito mode.

**Comment by merryman** [comment]
Turns out this was an issue introduced due to a chrome update. Fixed now.
