### ISSUE TITLE
Double Clicking a polygon leads to deformities

### ISSUE THREAD

**Issue by frcroth** [LivelyKernel/lively.next#246]
When double clicking a polygon morph multiple times, the polygon is changed, with the vertices property being affected. This leads to weird deformities. Most of the time some corners are cut leading to entirely new shapes.

**Comment by merryman** [comment]
This is most likely an accidental trigger of the add/remove vertex feature. This is odd, since usually this requires the vertices to be visible. I will investigate.

**Comment by merryman** [comment]
Fixed in: be422b
