### ISSUE TITLE
Keyboard shortcut labeled wrong

### ISSUE THREAD

**Issue by SilvanVerhoeven** [LivelyKernel/lively.next#25]
Pressing `Ctrl+K` in the world opens a window to select a workspace to open, `right click` on world > Tools > open workspace opens the JS workspace, though being labeled as `Ctrl+K`, too.

**Comment by merryman** [comment]
Yes this is somewhat related to #29 . Overall the menu needs to be redone, I haven’t gotten to that yet. Feel free to submit a PR if you can figure it out!

**Comment by linusha** [comment]
@merryman what would you say is the actually intended behavior? I figured out how to make it consistent at least, so for me "open workspace" in the world-menu opens up the same dialogue as pressing `Ctrl + K`. Is that how you think it should work?

**Comment by merryman** [comment]
Sounds good to me!
