### ISSUE TITLE
Opening the color picker throws errors

### ISSUE THREAD

**Issue by T4rikA** [LivelyKernel/lively.next#256]
When you open the color picker on a morph it throws svg errors as seen in the screenshot.

![image](https://user-images.githubusercontent.com/43680469/116060902-90c94180-a682-11eb-93ec-b858b7a21fa5.png)

**Comment by merryman** [comment]
This has been there for ever. It is a bug inside the svg renderer of morphic.

**Comment by merryman** [comment]
Fixed in ec04b9c1
