### ISSUE TITLE
Saving a world with an empty Class breaks on reload

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#258]
I created a world with a class  `SummaryScoreTable` and then moved its functionality to an enclosing object, so the class was still attached to a morph as an extension of Morph, but it had no functionality.  The world was blank on reload and @merryman had to fix it, and I told him I would open a ticket on this one.  @merryman  can discuss how he rescued the world.

**Comment by merryman** [comment]
This is now fixed as part of b08040c2b93487306f5f8fad368404de489934e1. It was due to a bug inside the scope parsing of a class definition. It assumed the body of a class to contain stuff.
