### ISSUE TITLE
What does "Edit as rich text" do?

### ISSUE THREAD

**Issue by frcroth** [LivelyKernel/lively.next#261]
When editing a label with the "Edit as rich text" option, a window appears that allows editing of the text. How can one edit rich text there, e.g. bold, italic?

There is a right click option "edit text attributes" on selected text, which does not change anything visually.

**Comment by merryman** [comment]
This is a pretty rough feature, but essentially you are able to edit the text via the rich text controls in the side bar.
The other option you are talking about is deprecated and should be removed.

**Comment by frcroth** [comment]
ok thanks
