### ISSUE TITLE
Getting an error when I try to import a module

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#268]
The module I'm trying to import is URL, and the error message that keeps coming up is this:
TypeError: Cannot read property name of "null"
ModuleInterface_addImports_ (https://matt.engagelively.com/lively.modules/src/module.js:779:44

Tracing the call through the Chrome debugger, the module is https://jspm.dev/npm:@jspm/core@2/nodelibs/url, and fromPackage is indeed null.  tracing beyond that doesn't get me very far.

Here's the line of code that got me in trouble: `const url = (new URL(document.location)).searchParams.get("dashboard")`
The funny thing is it worked fine in a javascript workspace.

The world is https://matt.engagelively.com/worlds/load?name=Dashboard%20Publication%20Development

and the snippet to browse is `$world.execCommand("open object editor", {target: $world.get("dashboard"), selectedClass: "PublishedDashboard"});`

**Comment by merryman** [comment]
You mean the publishing breaks when you try to add this import? Or the load breaks?

**Comment by merryman** [comment]
I do not get why you need to import URL at all. It is natively available in all browsers.
Maybe you just need to use `window.URL` ?

**Comment by rickmcgeer** [comment]
Maybe I should have used window.URL.  When I tried to save I got a fix prompt, and when I selected this things broken.  I'll use window.URL

**Comment by rickmcgeer** [comment]
I tried using URLSearchParams; it works, but the editor doesn't recognize it.  The snippet is
`const parameters = new URLSearchParams(document.location.search)`
which works fine, but since the editor doesn't know about URLSearchParams I am prompted for it.  Declare as global works fine.

**Comment by merryman** [comment]
This is expected behavior. I will close this issue then.
