### ISSUE TITLE
Hard to catch diagonal window resize cursor

### ISSUE THREAD

**Issue by SilvanVerhoeven** [LivelyKernel/lively.next#27]
At windows, e.g. the ObjectEditor, it's difficult to catch the point at which the window can be resized both at width and height. It would be helpful to make the sensitive area bigger, especially into horizontal direction.

**Comment by merryman** [comment]
Yes, that would be a general change to all the windows I suppose. I will look intro it.

**Comment by merryman** [comment]
I did some adjustments in c878045df0aa98cce70007e16732e7b9e37dcee6. Please try and confirm if this improves things.

**Comment by linusha** [comment]
There have been additional improvements to this situation.
What remains is mostly a chrome bug, that sometimes eats the resizer cursors completely.
