### ISSUE TITLE
Components not getting copied in a freeze

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#272]
It could well be a user issue, in which case guidance is needed.  The component galyleo/SliderFilter.json is not getting frozen with the Dashboard part in https://matt.engagelively.com/users/rick/published/dashboard, because it isn't used in the template world.  However, it can be used when a filter is loaded and the page is used.  So it may be we need the equivalent of a "requirements.txt" file in freezing, which indicates to the freezer what components to include.

**Comment by merryman** [comment]
This was a guidance issue, but I will document the resolut here:
The issue @rickmcgeer was running into is that the missing master components where neither referenced in the bundled code nor in the initial state of the app in question. In fact the references to the master components cam from 3rd party state that was read into the frozen app at runtime. This of course leaves the freezer clueless and there is no way to infer the requirement of these master components automatically.
A temporary fix is to make the bundler aware of these master components explicitly by adding some dead code that does nothing else but directly reference the required components like so:
```javascript
resource(‘part://path/to.master’)
```
This will do nothing a runtime, but make the bundler include the master components into the resulting artifact.
