### ISSUE TITLE
Fonts mismatched on components in editor and frozen page

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#274]
The world is Dashboard Publication Development on https://matt.engageLively.com, and the published page is https://matt.engagelively.com/users/rick/published/dashboard/index.html
![image](https://user-images.githubusercontent.com/656259/119021949-e24caf80-b954-11eb-9289-cda39db6bc27.png)

**Comment by merryman** [comment]
That just means your frozen page does not carry the font that the particular button is using. You should ensure it is installed on one of the morphs in your frozen morph.

**Comment by merryman** [comment]
This should now be fixed!
