### ISSUE TITLE
Weird text rendering on auto-complete

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#28]
Auto-completion also re-shows the word on which `Strg + Space` was pressed resulting in a overlap of both texts. This is a purely visual issue.

![autocomplete_lively](https://user-images.githubusercontent.com/14252419/96728364-57063e00-13b4-11eb-893d-a14414cd7457.png)

**Comment by frcroth** [comment]
I can reproduce this. 

![Screenshot_20201021_152856](https://user-images.githubusercontent.com/6863832/96728641-99c81600-13b4-11eb-9711-ce5408779e80.png)

**Comment by merryman** [comment]
This should be fixed in e25475457c606d15460e2373d0b1dbab92bfdb92
