### ISSUE TITLE
Frozen world not loading

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#282]
We saw this once with dashboard, and now I am seeing it consistently with coreshell.  The world is coreshell-5 on galyleobeta, and the two worlds not loading are https://galyleobeta.engagelively.com/users/rick/published/coreshellProcessor/index.html and 
https://galyleobeta.engagelively.com/users/rick/published/coreshellFrontEnd1/index.html.  The console error message is vry cryptic:
load.js:35 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.$jscomp.inherits (load.js:35)
    at load.js:3245
    at load.js:3250

Which seems to be in this function: 
$jscomp.inherits = function(Q, da) {
    Q.prototype = $jscomp.objectCreate(da.prototype);

apparently da is null, but I had no real luck tracing it.

I also put breakpoints in the onLoad() method, and they didn't get hit.

**Comment by merryman** [comment]
This is an already resolved issue that you encounter because you are not operating on the latest version of lively.next. Please ensure that you are actually on the latest version of the branch or confirm with @m-hemmings that he is sure the latest version is running.

**Comment by rickmcgeer** [comment]
I am using galyleobeta.  @m-hemmings , can you update to latest version?  And, @merryman , is there any easy way to see which version we're running?

**Comment by merryman** [comment]
I now added a version checker to the bottom left of every lively world that tells you when you need to update: 
![image](https://user-images.githubusercontent.com/1296388/120182121-45b8c600-c20e-11eb-9c19-1b8f52b8785c.png)
