### ISSUE TITLE
InteractiveTree: Cannot set font color of collapse icon

### ISSUE THREAD

**Issue by SilvanVerhoeven** [LivelyKernel/lively.next#283]
The color of the collapse icon (triangle) is always black when the item is not selected, regardless of the `nonSelectionFontColor`. On the other hand, `selectionFontColor` colors the icon on selection, as expected.

Possible approach: The color of the icon seems to be set in `recoverOriginalLine` (in `lively.components/tree.js`), which is derived from `attribute`. The latter holds multiple color values, including `nonSelectionFontColor`, but also black. I did not look into why this is and how this could/should be altered.
![grafik](https://user-images.githubusercontent.com/44174681/120200224-5f650800-c224-11eb-8744-40a29e5c4252.png)

**Comment by merryman** [comment]
Yes, I think there is still some things we have not really fleshed out with custom textAttributes + selection inside trees. @SilvanVerhoeven When you have some time to spare, can you write a comprehensive set of tests that illustrate this issue and what does not work? I think that would help us to narrow down where the semantics go off the rails here.

**Comment by merryman** [comment]
@SilvanVerhoeven Any updates on this one?
