### ISSUE TITLE
Version indicator wants to update on the newest commit

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#285]
I am on the latest master with unstaged changes in my index. For science I tried with the master directly from here and with our fork, both on the newest commit.

The version indicator asks me to update. Clicking it does not resolve this.

![Screenshot (1)](https://user-images.githubusercontent.com/14252419/120231226-3dce4580-c251-11eb-95fa-e45cee99e17a.png)

`git rev-parse master origin` leads to the following output:

```
be8d8f376206381d5b44d1201427a7ce98c63f45
f5303a241fcee9b62c4c353600689bc3d4d7b6a3
```
The problem remains.

**Comment by merryman** [comment]
I wonder what that f5303a241fcee9b62c4c353600689bc3d4d7b6a3 points to.

**Comment by linusha** [comment]
With the new change to the GitHub API today this (unsurprisingly I guess) works for me now.
