### ISSUE TITLE
Halo Movement via dragging resizing halo

### ISSUE THREAD

**Issue by frcroth** [LivelyKernel/lively.next#287]
In many tools, such as PowerPoint it is possible to move objects via dragging of a "resizing halo" at the border, next to the resizing handles. This may be nice in lively as well.

**Comment by merryman** [comment]
I am not sure I understand correctly but you can already drag the object around by dragging the drag halo?

**Comment by frcroth** [comment]
Yes, which is not perceived as intuitive by new users, since it is not used in other tools.

**Comment by linusha** [comment]
Yes, this is something that came up in our very first user tests I believe. Ofc the halo exists, but it is contrary to what one is expecting coming from other tools. In e.g. power point one can grab a rectangle by the border and move it this way.

**Comment by merryman** [comment]
I see! Well I think we can add support for that. Any volunteers?

**Comment by merryman** [comment]
This should now be implemented 8566045a
