### ISSUE TITLE
Target picker sometimes triggers onMouseUp

### ISSUE THREAD

**Issue by frcroth** [LivelyKernel/lively.next#288]
Especially when holding the click a little longer. I think this is undesired behavior, since onMouseDown is prevented as well.

https://user-images.githubusercontent.com/6863832/120607482-81db6900-c450-11eb-8ba4-4ff3ac7964a4.mp4

**Comment by merryman** [comment]
We can solve this easily by making the target selection effective, and also the picker disappear on onMouseUp.

**Comment by frcroth** [comment]
Is this a change you agree with?

**Comment by merryman** [comment]
Yes! (Sorry if that was not clear from the previous response.)
