### ISSUE TITLE
Context Menu startStepping broken?

### ISSUE THREAD

**Issue by JensLincke** [LivelyKernel/lively.next#29]
```[lively.modules] Updating registry Ball@0.1.0 => Ball@0.1.1-0
:9011/lively.ide/world.js:282 Set global "that" to <Ball - anEllipse>
:9011/lively.ide/world.js:924 TypeError: (intermediate value) is not iterable

    at MenuItem.eval (:9011/lively.ide/world.js:1229)
    at async MenuItem.onMouseDown (:9011/lively.components/menus.js:121)
setStatusMessage @ :9011/lively.ide/world.js:924
```

**Comment by JensLincke** [comment]
![image](https://user-images.githubusercontent.com/1466247/96737601-262b0680-13be-11eb-8fbf-678e7f202a44.png)

**Comment by JensLincke** [comment]
maybe it is sommething with the whole menu, because custom connects did also not work

**Comment by merryman** [comment]
Yes, the menu needs to be refactored and cleaned up. I focused solely on the more “visual” interface elements the past couple months, so I guess some of the menu commands got under the rails somehow.

**Comment by merryman** [comment]
This is fixed now.
