### ISSUE TITLE
Color chooser has multiple issues

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#294]
1. The most obvious is that the general rule of any widget is that once a value is chosen, the widget disappears.  I can see the use case for leaving it up (lets people experiment), but it isn't the usual behavior, and thus it doesn't meet user expectations.
2. I've had cases (it's rare) where the top-right corner of the harmonies widget is off-screen, and in this case it can only be closed by getting a halo and using the garbage can, or dragging until it appears.
3. One thought is that the harmonies tool should have an RGB text entry box, and the RGB text entry should have the value of any selected color.
4. The harmonies box could have a custom-colors row, a la Google color chooser

**Comment by merryman** [comment]
Addressed now with the new color picker in 162499e6d7bc02f83b2f18e53f23727f8f2cce5d. I dropped the color harmonies though. Never ended up using them.
