### ISSUE TITLE
Number Widget unit is not shown after deserialization

### ISSUE THREAD

**Issue by frcroth** [LivelyKernel/lively.next#295]
When setting a unit on a NumberWidget, that unit is not shown immediately.

When saving a World with a NumberWidget that has a unit and loading, that unit is gone. It is only shown after changing the value again. This can also be achieved with a relayout call.

**Comment by merryman** [comment]
@Paula-Kli can you maybe look into wether or not this is related to the recent PR: https://github.com/LivelyKernel/lively.next/pull/292 ?

**Comment by Paula-Kli** [comment]
I think this is a similar issue as #290 as there realyout was not triggered as well

**Comment by merryman** [comment]
So it seems like #292 did not squash the bug sufficiently?

**Comment by Paula-Kli** [comment]
#292 was about setting min and max of the NumberWidget and this bug is imo
