### ISSUE TITLE
World does not load

### ISSUE THREAD

**Issue by frcroth** [LivelyKernel/lively.next#298]
Recently (approx. 1 week) loading a new world sometimes fails, as it halts on loading the top bar. This does not happen every time, and retrying to load a new world mostly fixes the issue. No error is shown in the console.

![image](https://user-images.githubusercontent.com/6863832/121878695-4ec88d80-cd0c-11eb-93f1-38523cbf72eb.png)

**Comment by merryman** [comment]
Is this still the issue for on the latest version of master?

**Comment by frcroth** [comment]
Did not come up recently. But then again I have not used lively in the last few weeks.
