### ISSUE TITLE
Should be able to read and edit markdown files inside System Browser

### ISSUE THREAD

**Issue by frcroth** [LivelyKernel/lively.next#299]
Markdown files are often used for code documentation and it would be nice to make them readable in the browser like other files. Markdown styling would be nice, but is not necessary.

**Comment by merryman** [comment]
We already have that capability, it is just not exposed in a straight forward manner. When you open a markdown file with the text editor, we already have mardown syntax highlighting enabled out of the box. The editor also supports markdown export to html in a window via command. Just right click on the markdown code and select "convert to html".

**Comment by frcroth** [comment]
Yes but Markdown files are not shown in the browser as files, only jsons and js files are listed

**Comment by merryman** [comment]
Ah! Gotcha. Renamed the title accordingly.

**Comment by merryman** [comment]
This is now supported with the new system browser! I will add more features (like live preview) in the future.

**Comment by frcroth** [comment]
nice!
