### ISSUE TITLE
Dependencies not installed

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#3]
The following npm packages were required but not automatically installed by the script: node-fetch and brotli.  This was easily worked around by:

$ npm install node-fetch 
$ npm install brotli

Found on a Macbook Pro 14,2:

  Processor Name:	Dual-Core Intel Core i5
  Processor Speed:	3.1 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  
 System Version:	macOS 10.15.6 (19G2021)
  Kernel Version:	Darwin 19.6.0

rick-mac:lively.next rick$ npm --version
6.14.8
rick-mac:lively.next rick$ node --version
v12.18.3
rick-mac:lively.next rick$

**Comment by merryman** [comment]
Did this happen when you just ran ./install.sh from the terminal? Or did you happen to use another command? install.sh basically already does what you have been doing so I am wondering what could go on.

**Comment by merryman** [comment]
Nevermind, this was due to an non existent directory I accidentally added to the PATH during install. Should be fixed in: 3bb759051faa3c4a711b
