### ISSUE TITLE
default width of workspace under windows to small

### ISSUE THREAD

**Issue by JensLincke** [LivelyKernel/lively.next#30]
![image](https://user-images.githubusercontent.com/1466247/96737868-7013ec80-13be-11eb-85be-bba4042c7e8a.png)

**Comment by linusha** [comment]
This seems to not be related to windows. Behaves the same way for me on Linux:
`Chromium 85.0.4183.121 Built on Ubuntu , running on Ubuntu 18.04
`

**Comment by merryman** [comment]
Seems like your font is slightly larger then on MacOS. Can you inspect the text morphs and tell me what font size it renders?

**Comment by linusha** [comment]
The `fontSize` property of the editor says 16. That is just large enough to mess up the line-length, with 15 it does not break.

**Comment by merryman** [comment]
That's way too large. Mine is 12 on Mac OS. The workspace derives its font size from the config. Can you evaluate `import { config } from "lively.morphic";
config.codeEditor.defaultStyle.fontSize` and tell me what it returns?

**Comment by linusha** [comment]
> That's way too large. Mine is 12 on Mac OS. The workspace derives its font size from the config. Can you evaluate `import { config } from "lively.morphic"; config.codeEditor.defaultStyle.fontSize` and tell me what it returns?

16 as well.

**Comment by merryman** [comment]
Okay, for some reason there was a ternary expression that assigned 16 for all platforms not on Mac OS. No idea what was going on here, but maybe someone on windows liked fonts to be larger? I undid that in ca84aa024d761862876e64b32b8a2760dc5310dc. This was once already done in 6f1eda6a1a821b5806ab4fb2dc2471509a1bd961, but then seems to have gotten lost in 6fe5f07c91a59aeca3b80b9082976807314c39a1.
