### ISSUE TITLE
Comment Browser errors upon renaming morph via GUI

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#307]
When changing the name of a morph via its halo, the Comment Browser throws the following error message:

![Screenshot (1)](https://user-images.githubusercontent.com/14252419/125429943-a3b401b3-8d6f-480d-bf57-62669192596e.png)

@merryman I will look into this, but I cannot promise that it will happen super fast.

**Comment by frcroth** [comment]
Could not reproduce this.
I created a morph, opened the comment browser, added a comment, renamed the morph, no error

**Comment by linusha** [comment]
Yes, opening the Comment Browser once fixes this for me too.
In a fresh world, in which the comment browser has not been opened, the above error persists for me.
