### ISSUE TITLE
CommentBrowser should not be saved in the world

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#313]
This is an issue that we opened some time ago in a project-internal repository, when working on the comment browser. It makes more sense to move it here. 

> Snapshots contain commentBrowser and all its submorphs, cluttering the snapshot.
> The alternative is creating a new commentBrowser each time on world load.

The commentBrowser is implemented as a singleton, and created once per world. It is probably beneficial to create it once per world per load "session".

**Comment by merryman** [comment]
In fact the singelton makes that a little messy. What you can to is to subscribe to the global event emitter ('lively.notifications')  and listen for `'world/loaded'` to replace the singleton on a world load.

**Comment by linusha** [comment]
Closed with 2f80ebee06f4f585a599dce1e85344c91493a06a
