### ISSUE TITLE
Still difficult to enter text in a text morph

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#314]
I add a text morph, then  click in it and start typing, nothing happens.  Double-click and nothing happens.  Select, double-click, again nothing.  However, when I initialize (through the sidebar, a JavaScript window, an inspector) with <morph>.textString = <string> and then subsequently edit, everything works well.

**Comment by merryman** [comment]
Yes, there problem here:

1. After text morph creation via top bar the morph does not focus to edit.
2. Initial double click should directly fast forward to edit, which it currently does not.
3. The selection should be dropped by default when the focus of a text morph is lost that has been temporarily edited.

Will fix asap.

**Comment by linusha** [comment]
Closed, as these points have been consumed by #379.
