### ISSUE TITLE
Clicking on Scene graph/Styling Palette selects morphs underneath...

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#315]
This also happens sometimes with the color popups.  See the attached screenshot: I clicked on a name in the scene graph and another object was selected because it was underneath the scene graph.
![image](https://user-images.githubusercontent.com/656259/130376535-478e64fe-9951-4114-b7e8-000d8b410703.png)

**Comment by merryman** [comment]
This is fixed now.
