### ISSUE TITLE
Need a better interface for large applications

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#319]
This issue is for discussion, not any immediate action.  The Galyleo Dashboard is probably the largest application ever written in Lively, and it's straining the Lively architecture.  Specifically, the Lively UI really pushes developers to attach all code to physical objects, and what this results in is large, complex objects which should be factored.  The problem is that most of the components have no physical realization, or the logic is almost completely divorced from the physical realization.  
At an abstract level, what we're finding is that some objects are suited to an MVC architecture, and some a Morphic architecture.  So our system should support _both_ architectures in a clean way.  I appreciate this isn't easy, which is why I'm raising it for discussion, not action.

**Comment by linusha** [comment]
As we have the "new" component architecture now, I will close this.
This still raises a valid point, namely, that the more we embrace the new component architecture, the more we loose support for the snapshot/object based "tinkering" approached.

This is something we have in mind, but that I do not deem apt for a ticket.
