### ISSUE TITLE
naming a text log, will get it filled with a log?

### ISSUE THREAD

**Issue by JensLincke** [LivelyKernel/lively.next#32]
![image](https://user-images.githubusercontent.com/1466247/96744689-99844680-13c5-11eb-989a-addf943f8e54.png)

it generates weired code inside the object

**Comment by merryman** [comment]
Are you thinking of the textString property of textMorphs? There is no real textContent property within morphic in lively.next I am aware of.

**Comment by JensLincke** [comment]
I thought of textString... thankt. But even if it would be undefined... what happend to my text?

**Comment by merryman** [comment]
That on the other hand seems really odd. Can you recover the steps that you did to get there? I cant really reproduce this locally.

**Comment by JensLincke** [comment]
I dragged out a text, named it "log" and evaluated "textContent" on it.

It might be a side effect of naming it "log"

https://www.dropbox.com/s/yiblgguawr0tu0m/Y53gzFqi3S.mp4?dl=0

**Comment by merryman** [comment]
Looks like a present Robert left for us: c98366ba093b96cdbd68b985147d93b70764001b ;-)

**Comment by rksm** [comment]
ahhhh the good old times!

**Comment by JensLincke** [comment]
Hello Robert :-) Do you remember if this was important? Or "kann das weg?" :-)

**Comment by rksm** [comment]
Well, it was a hack to quickly debug code rewriting. When you open a "log" and evaluate stuff it will print the transpiled code.

It _might_ have been used in other places but nothing that _should_ break...

Sollte also weg können...
