### ISSUE TITLE
Selecting Text does not always shift the viewport of the sourceEditor

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#323]
I tested this in the SystemBrowser and the ObjectEditor.
When selecting Text with the keyboard, e.g., Shift+Down Arrow, the end of the selection is not always visible in the editor.
The viewport of the Editor is shifted only upon lifting the down arrow key.

I would expect the end of the selection to always be visible.

**Comment by linusha** [comment]
Okay, I found the relevant section in the code. @merryman I assume that this does not happen was a conscious decision because of performance implications?

I changes the part in my setup so that it does effectively not get debounced. I'll report back after working with it for a while :)

```
function cleanupScroll (morph) {
      const scrollCursorIntoView = command.hasOwnProperty('scrollCursorIntoView')
        ? command.scrollCursorIntoView
        : true;
      if (scrollCursorIntoView) {
        fun.debounceNamed('execCommand-scrollCursorIntoView-' + morph.id, 1, () =>
          morph.scrollCursorIntoView()
        )();
      }
    }
```

**Comment by merryman** [comment]
> Okay, I found the relevant section in the code. @merryman I assume that this does not happen was a conscious decision because of performance implications?
Yes! However that line of code is quite a bit old so the performance problems back then may have been resolved by now. I will keep this open until we deem this safe to remove.
