### ISSUE TITLE
"Choose module" dialogue should always be in front of browser

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#325]
I am not sure exactly why this happens so often to me with the new browser, but in the last few days I often "loose" the Choose module dialogue behind the browser window, which is a bit annoying. To reproduce this, just open the dialogue and click somewhere in the browser.

Possible solutions I propose are either making it so that this dialogue is always in front of the browser or clearing the fader (and thus closing the dialogue) upon clicking in the browser.

**Comment by merryman** [comment]
Fixed in 2c190cc4
