### ISSUE TITLE
Components getting resized, text changed, new items added, etc

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#326]
The problem is that Components lose styling when they are saved: elements are repositioned, text changes color and size, and so on.  Here's an example from the world DAN3 on https://matt.engageLively.com:
![image](https://user-images.githubusercontent.com/656259/133849090-7b77e3ae-abd5-4398-a9c1-851944804047.png)
When I open it from the component browser here is what I see:
![image](https://user-images.githubusercontent.com/656259/133849554-cfc68466-24df-40ea-b4b4-beb9570c5ae4.png)
Pulling it out of the window makes it clear what's happening:
![image](https://user-images.githubusercontent.com/656259/133849720-0333d209-b8ca-4a7a-a3cb-5bc8f3b592d3.png)
I think what has happened here is that I took a component in another world, made an instance of it, then copied that to the new world, modified it and made a component of that -- and some of the history from the previous instance was kept.  I will leave this component (bmiMeter) intact, and build a new component from scratch.  This way the bad component will be available for debugging.
World is https://matt.engagelively.com/worlds/load?name=DAN3

**Comment by merryman** [comment]
I think this is pretty much related to the previous issues you encountered with master components as in #322. This will hopefully be solved when we start to move away from storing master component stateful inside worlds and instead make them represented as declarative description in code.

**Comment by merryman** [comment]
I am closing this one since the preliminary transition to file based master component definition is nearing completion.
