### ISSUE TITLE
Worlds cannot be saved

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#33]
I just pulled the latest master. When trying to save the world (regardless whether I try to save as `JSON` or `MorphicDB` the following error appears and it is not possible for me to save worlds.

![saving_worlds_error](https://user-images.githubusercontent.com/14252419/96842077-e3643f80-144c-11eb-856e-b801081901a7.png)

This is obviously not optimal, but if this is not reproducible/... I am happy to just switch to the old commit that I had pulled locally, since it worked there. If that helps I could also figure out which one that was.

Running on `Chromium 85.0.4183.121 Built on Ubuntu , running on Ubuntu 18.04`

**Comment by merryman** [comment]
This issue was already fixed back in a6469538df6b7a69c54f50e7b36c20a8c77b3a3d. Somehow it looks like you are on a much older revision. Have you cleared the local storage?
