### ISSUE TITLE
Bundling Assets (particularly images) with components

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#330]
This is a long-term enhancement request; I imagine it will take awhile to do it.  When I build an object, I often include images.  I want the URL for the image to be persistent, and the easiest way to do that is to ensure that the image is in the same directory (or a closely-related directory) to the world.  In standard web apps, this is accomplished by having a relative path in the URL (../assets/myImage.png, e.g.).  This has plusses and minuses; it relies on the directory structure remaining intact.  But the way things are now, we're encouraged to keep the image separate from the world, which is an invitation to broken links down the road.

**Comment by merryman** [comment]
What we want is a canonical asset management in lively. Right now it is all over the place, with different conventions of using certain directories (assets directory in morphic, user upload directories in worlds, font urls attached to morphs) and there is not guarantee that you keep everything reliably together when moving on to deploy a certain morph or moving a project between systems. If we provide in lively a canonical asset manager, which interfaces with the freezer as well as the project management (git repos/local worlds) and tools everywhere, we should be able to solve this once and for all. Keeping this around for when I get to work on this again.
