### ISSUE TITLE
Weird Button Label in Save World-Dialogue

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#34]
In the "Save World" Dialogue the Dropdown for MorphicDB/JSON is initially labeled "aButton". It is possible to select either one of those and the text changes accordingly, so this is just the initial text that is weird.

![save_world](https://user-images.githubusercontent.com/14252419/96842580-81580a00-144d-11eb-866b-cb85d73178dd.png)

Running current master on `Chromium 85.0.4183.121 Built on Ubuntu , running on Ubuntu 18.04`

e: might this be related to #33 ?

**Comment by merryman** [comment]
This is weird. Similar to #33 it looks like somehow you are on a much older revision somehow. I will try to reproduce this locally first.

**Comment by linusha** [comment]
> This is weird. Similar to #33 it looks like somehow you are on a much older revision somehow. I will try to reproduce this locally first.

@merryman I just tried it again in incognito mode and you were right that it works like a charm there. I pulled the changes from the last 2 weeks or so this morning, and then did not clear my local storage. So I guess this works as expected. Sorry for that!
