### ISSUE TITLE
Font resetting in published world

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#344]
This shows up in narrow mode on the world [https://matt.engagelively.com/users/rick/published/DANNew/index.htm](https://matt.engagelively.com/users/rick/published/DANNew/index.htm).  The world is [https://matt.engagelively.com/worlds/load?name=DAN4_2](https://matt.engagelively.com/worlds/load?name=DAN4_2).  The Experience Card as a label "Done required training for dive?"  It is white, 16pt san-serif.  In wide mode, it shows up fine, and in narrow mode in the edit world (https://matt.engagelively.com/worlds/load?name=DAN4_2).  In narrow mode on the published world it is smaller, and black.  Both narrow and wide mode use the same component (part://$world/equipmentCard).  Here are the screenshots:
1. Wide mode, editor: 
![image](https://user-images.githubusercontent.com/656259/142737586-cf848c42-831e-4c27-9022-2a1a5d269811.png)

2. Narrow mode, editor: 
![image](https://user-images.githubusercontent.com/656259/142737596-c00140ec-e391-4733-9c10-b6ef40cc26da.png)

3. Wide modem published: 
![image](https://user-images.githubusercontent.com/656259/142737601-347db239-d0b1-4a95-b42e-a10d4fdfcd8c.png)

4. Narrow mode, published, font problem highlighted: 
![image](https://user-images.githubusercontent.com/656259/142737605-c899d23c-3aa3-4edf-a4a6-b5fbe8789659.png)

**Comment by merryman** [comment]
The problem is that you renamed the label inside the morph derived from the component. This lead the component system into an inconsistent state where I thought the label was still stylized by the master component but because of the differing name, no style could be found. I will push a fix to that soon.
