### ISSUE TITLE
Numpadenter should be equivalent to Enter as a keystroke for text inputs

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#360]
At the moment, a text component, notably InputLine, accepts Enter as text accepted, but not Numpadenter.  (This is the key code when the Enter key on the number pad on the right side of many keyboards is hit).

**Comment by linusha** [comment]
This should be fixed with f6748964570118b5d3ac72d49ea77fa8b5851dc4.
