### ISSUE TITLE
Limitations of custom module cache

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#365]
In 63468128fed3f465a7b407ac75061e88010d0e10 the possibility to cache modules loaded from jspm locally, i.e. on drive was added.
There are some conceptual/implementation wise limitations with the current state:

1. HEAD requests failing loudly in the console.

Since the cache mechanism is implemented 100% client side, the only option to check whether a file already exists (i.e. is it cached or not) it by performing a HEAD request. When the file is not yet cached, this request will obviously fail, which will in turn cause a lot of error messages in the console. This can be mitigated, by once informing the cache from the server which files currently exist in the cache. For these, HEAD requests would then not be needed anymore.
By preversing and appending to this state when files are added to the cache during runtime, we probably could reduce the amount of failing requests to zero.

2. imports need a host (i.e. `esm://cache/package@1.2.3.` instead of `esm://package@1.2.3.`)

We first thought that this was only a problem with rewriting import/exports statements in the loaded modules so that we can always guarantee a host for systemJS. However, there is a more complex problem at play here: 

Even when rewriting everything correctly, systemJS will subsequently only detect the version number `1.2.3.` in the above example as a host, as it (correctly) interpretes the part after `@` as a host when `foo@bar` comes after the protocol. This might be fixable, but would need in-depth hacking of SystemJS. As we want to update SystemJS anyways, and this will mean chaging all hook code etc. we decided to only afterwards look at this problem.

**Comment by linusha** [comment]
Regarding Point 2:

The code nececessary to achieve the rewriting (so to get everything to work until the host-resolution of systemJS kicks in) can be found on the `esm-cache-rewrite-imports` branch. 
It implements the following logic:

**Case 1** When writing a "toplevel", custom created index.js:
- `./...` becomes `esm://`

**Case 2** When rewriting any file:
- `/...` becomes `esm://`

`**..**/...` should _never_ be rewritten.

**Comment by linusha** [comment]
- local bundling without internet is not supported

**Comment by merryman** [comment]
We can thing about tackling 1.) with a dedicated subserver that manages the esm cache. Regarding 2.) it is way too much effort for the benefit it creates.

With regards to the local bundling issue @linusha will investigate wether or not that is still the case.

**Comment by linusha** [comment]
Offline bundling works since #1169.

While tackling 1) would be possible, the generated value seems to be extremely small. We decided against implementing this at the moment. HEAD requests failing in the console will persist, as `exists()` calls on `resources` utilize those as well.

Additionally, the `esm://cache` is now already quite populated after the initial bundling during the process of running `install.sh`.
