### ISSUE TITLE
Packages loaded from jspm that are executed in a node context 

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#368]
Currently, we e.g. load semver via JSPM in `lively.modules`.
When bundling `lively.modules` to use the most current version when bootstrapping the system, this leads to breakage, since jspm delivers all code in a way that is executable in browser.

The correct solution for this might simply be to not load code that is run via node from jspm.

**Long-term, this leads to us needing a system to keep the bundled versions of e.g. `lively.modules` up to date,** e.g. by using a git hook. This is probably only realistic to tackle after updating the freezer is done. Then, this should probably become its own ticket.

**Comment by merryman** [comment]
I believe this was finally resolved in #1117, since we are now no longer importing any modules form jspm within the node context. Correct me if I miss something, but if that is not longer the case, I think we can close this? @linusha.
