### ISSUE TITLE
left style pallete goes beyond scroll area and back

### ISSUE THREAD

**Issue by JensLincke** [LivelyKernel/lively.next#37]
![image](https://user-images.githubusercontent.com/1466247/96869362-a3fb1a80-146f-11eb-869f-45e539552238.png)
and it looks like this and wiggles

**Comment by merryman** [comment]
That palette is a mess. I will fix that as part of the general input widget makeover.

**Comment by merryman** [comment]
Palette is now completely replaced (see 162499e6d7bc02f83b2f18e53f23727f8f2cce5d). Closing this now. New funny behavior related to the new color picker should go in a separate issue.
