### ISSUE TITLE
The demo of lively.vm does not work

### ISSUE THREAD

**Issue by wwj718** [LivelyKernel/lively.next#374]
[The demo of lively.vm](https://livelykernel.github.io/lively.vm/) does not work. (the link is from [here](https://github.com/LivelyKernel/lively.next/tree/master/lively.vm))

**Comment by merryman** [comment]
We will fix this as soon as possible. Right now we are refactoring a bunch of stuff in the core modules, and this website was referencing a particular build artefact in the trunk. Thank's for the heads up!
