### ISSUE TITLE
Problem with window resizers after saving and loading a world

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#376]
The attached video showcases several problems, although 3. might be unrelated to the cause.

1. After loading a saved world, the resizers at the outer edges of windows are white. They become transparent as long as one clicks/drags the window around.
2. Resizing these windows does no longer work.
3. In the displayed workspace, one cannot scroll anymore and the font has changed.

All these problems do not exist in newly created windows, i.e. it is a problem with the deserialization.

https://user-images.githubusercontent.com/14252419/163194000-7b88841f-737a-48a0-88a0-cae9fa3a7b59.mp4

**Comment by merryman** [comment]
Closing this now, since this has been fixed by now.
