### ISSUE TITLE
clicking and small dragging in text mode should not create text

### ISSUE THREAD

**Issue by JensLincke** [LivelyKernel/lively.next#39]
![image](https://user-images.githubusercontent.com/1466247/96891861-5db2b500-1489-11eb-824e-6216c9d15875.png)
I think I don't like those blue little points. Maybe only a significant drag should create objects in the first place?

**Comment by merryman** [comment]
Good idea, I will add a threshold.

**Comment by merryman** [comment]
Is added to the system now a while ago.
