### ISSUE TITLE
Component Cache not found

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#4]
Clicking on the three-cube icon (right icon on menu bar) gives a cache-not-found error:
![Screen Shot 2020-10-07 at 10 25 49](https://user-images.githubusercontent.com/656259/95365948-9d717e00-0887-11eb-9bfe-af446bf634f3.png)
![Screen Shot 2020-10-07 at 10 21 44](https://user-images.githubusercontent.com/656259/95365954-a06c6e80-0887-11eb-85b2-9eeef623737c.png)

**Comment by merryman** [comment]
This was due to a missing update policy of the index in the backend. Fixed in 03d17b5a4e188b9e068e3ed8b2b9059b5474335d.
