### ISSUE TITLE
Search in code jumps does not allow edit at found code

### ISSUE THREAD

**Issue by frcroth** [LivelyKernel/lively.next#40]
When I search for a specific term in the code opened in the browser, and the search finds the term, I may want to edit in that place. This is however not possible, as clicking back into the editable code closes the search and returns me to the situation I was in before the search. 

This is unexpected behavior, as other text editors do not act in such a way. Also this makes coding somewhat harder.

**Comment by linusha** [comment]
We are talking about searching code with Strg+F? In that case I have the same problem and agree with the assesment of @frcroth.

**Comment by frcroth** [comment]
> We are talking about searching code with Strg+F? In that case I have the same problem and agree with the assesment of @frcroth.

Yes that's what I'm talking about. You can click on the check button as I just realized, but the default behavior is jumping back to start.

**Comment by merryman** [comment]
I have to agree. I remember how this used to drive me crazy, however I must have gotten used to it over time. I am open to changing the behavior. My understanding is, that the code search purely wants to be operated on via the find and replace interface it exposes. The fact that it jumps back to where you started is in fact a "feature" albeit one that a lot of users are getting confused by.

**Comment by linusha** [comment]
@merryman what is our desired end-result here? I have the "jumping back" now disabled locally.

However, that also makes the "check" button redundant I think. My proposal would be:
- scrap the "accept" button entirely, as we can always click anywhere in the code to jump to that position directly
- keep the "cancel" button. clicking that would reset the state of the code editor to the one before the search (meaning its functionality stays as it is)
- clicking anywhere in the code cancels the current search but puts the cursor at the clicked position (as @frcroth and I would have expected)

If we know what the desired behavior is I will make a PR ready!

**Comment by merryman** [comment]
Sounds good to me!

**Comment by linusha** [comment]
This can be closed, I again forgot to mention it in #228. :disappointed:
