### ISSUE TITLE
Namespaces not being exposed in imported module

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#41]
This is probably a documentation request rather than a bug.  I used the sidebar to import the papaparse CSV parser.  According to the papaparse documentation, the module's code is exposed in the namespace Papa.  See https://www.papaparse.com/.  However, when I try a simple test, 'Papa' is undefined.  See attached screenshot, and note the module has been imported.
![image](https://user-images.githubusercontent.com/656259/97093670-ce311180-1602-11eb-85d8-35ebae4f997a.png)

**Comment by merryman** [comment]
When I import the library like this, everything works fine: `import papa from "https://jspm.dev/papaparse"`
A general rule of thumb: jspm tries to export the interface usually via the default export mechanism.
So do not do `import { member } from "https://jspm.dev/modulename"` but instead something like `import module from "https://jspm.dev/modulename"`
