### ISSUE TITLE
Line numbers

### ISSUE THREAD

**Issue by frcroth** [LivelyKernel/lively.next#42]
Errors show line numbers to identify where the error occurred. However there does not seem a way to quickly find the spot in the code, as line numbers are not shown in the code editor. 

Line numbers could be shown to the right of the code or as a cursor position in the meta text info in the browser.

**Comment by merryman** [comment]
I can add that quickly as a simple addition to the code browser. But that only updates on explicitly placing the cursor with the mouse for now. For a more holistic approach, take a look at the debug layer of the text morphs and how it is rendered. The debug layer can be triggered via `textMorph.debug = true`;

**Comment by linusha** [comment]
Closed, as it is covered by https://github.com/LivelyKernel/lively.next/issues/378.
