### ISSUE TITLE
Make Port Configurable

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#427]
It would be nice to easily start the server on a port other than 9011.
The ./start.sh script and the docker file should accept port as an argument.
Most of the "infrastructure" necessary for this is already present. We mainly need to expose an argument and also check where and why the port is hardcoded in the code!

**Comment by merryman** [comment]
The port is configurabel. Check the `config.js`.

**Comment by merryman** [comment]
Can this be closed @linusha ?
