### ISSUE TITLE
Selection of text not possible

### ISSUE THREAD

**Issue by frcroth** [LivelyKernel/lively.next#43]
Selecting the beginning of a text is not possible if it is written right at the edge of a window, it seems like resizing prohibits this.

![ezgif-6-58cf506f0a29](https://user-images.githubusercontent.com/6863832/97094461-33adee00-1655-11eb-8bf2-667c084c96a7.gif)

**Comment by linusha** [comment]
I believe this is related to c878045df0aa98cce70007e16732e7b9e37dcee6.

**Comment by merryman** [comment]
Yes, this can be fixed if we disable the resize handles of the window when the window detects a mouse down that is not directed at one of the resize handles.

**Comment by merryman** [comment]
Fixed in 9aa440b
