### ISSUE TITLE
Number Widgets should adhere to text editing conventions in browser

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#436]
One of the **really** great things about text morphs in lively.next is, that they adhere to the conventions established by native browser editing fields. For example, double clicking a word will select that word, whereas a clicking thrice with select the whole line.

Number Widgets should to that too. Right now, e.g., changing the values in the properties panel is quite painful, if one wants to edit the numbers and not use the scrubbing behavior.

 I have not thought this through entirely, but the problem is more or less, that the NumberWidget itself is a simple Morph. We could think about delegating mousedown events on the widget to its Scrubber, which is a subclass of Text.

**Comment by merryman** [comment]
I have done some simple adjustments which you can review in #444.
Basically it involved implementing a simple blur handle on the scrubber and making it selectable.
