### ISSUE TITLE
New Connection on sidebar confusing and unintuitive

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#49]
I find the New Connection using the sidebar confusing, since it doesn't populate the source and target variables in the dialog.

**Comment by merryman** [comment]
I will add that in. However I have found the world menu solution to be extremely inconvenient, since it is very hard to track down the proper target/source property on selection. I will replace those with filterable list prompts instead.

**Comment by merryman** [comment]
@rickmcgeer can you reiterate if that confusion still holds with the current stage of the system? Thanks!

**Comment by linusha** [comment]
Currently, all visual assistance for the creation and inspection of connections are gone.
