### ISSUE TITLE
Bugs in Sidebars

### ISSUE THREAD

**Issue by merryman** [LivelyKernel/lively.next#490]
Collection of various things that need fixing in the side bars. This is a note mostly for myself to track.

- [x] dropping morphs on the scene graph is broken
- [x] custom properties in properties panel enforce incorrect default values on newly selected targets.
- [x] tooltips in properties panel are incorrect
- [x] rich text editing panel is broken
- [ ] #516
- [x] some popups are not declared to be epi morphs and can be selected in halo mode
- [x] history (back and forwards button) in the System Browser gets screwed up once we navigate to another module via the "browse modules" command

**Comment by linusha** [comment]
> custom properties in properties panel enforce incorrect default values on newly selected targets.

I cannot reproduce this anymore.

**Comment by linusha** [comment]
The restructuring of the LayoutControls has been moved to #516.
