### ISSUE TITLE
something error when opening PartsBin

### ISSUE THREAD

**Issue by wwj718** [LivelyKernel/lively.next#5]
![image](https://user-images.githubusercontent.com/3153878/95701370-02f4ae80-0c7c-11eb-8cd2-f548dcdf05e0.png)

run with : 

`docker run -d --restart=unless-stopped --name lively-next -p 9011:9011 engagelively/lively-next:alpha3`

**Comment by merryman** [comment]
We recently deprecated the partsbin and replaced it with **Master Components**.  You now define parts by declaring master components in your world. You can use these master components to define reusable styling entities and/or behavioral objects such as was the case with parts. You can import master components or morphs derived from them into other worlds. Importing can be done by opening the icon with the three boxes in the top menu bar. Then you can browse for exported master components in the core worlds or other of your own worlds.

To declare a part a master component (and make it exported from that world), with the part in question selected, click on the halo item with the box on it. This will make the halo appear in a pink color, denoting that the part is now a master component.
Once you save the world, you can then import that master component from other worlds.

I hope that helps!

**Comment by wwj718** [comment]
@merryman  thanks
