### ISSUE TITLE
Sourcetransform necessary for parts/components are not available in workspaces

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#510]
They are currently only run in .cp.js files. It should be possible to define components that contains parts in workspaces as well.

**Comment by merryman** [comment]
Aside from supporting the definition of components inside a workspace, it would also be nice to support the direct manipulation + reconciliation for the workspace.
Here again, we would face the nasty conflict between textual editing and direct manipulation, forcing the user again to temporarily pause the direct manipulation of components while they are editing.
One solution for mitigating this issue would be to introduce the concept of tiles (similar to the ones found in Jupyer Notebooks) where the component definitions can be isolated, so editing other tiles does not interfere with the direct manipulation session for editing a component.
