### ISSUE TITLE
Connections don't seem to be working on PC on Chrome

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#54]
I have connected the selection property of an HTML List to the value text, and it's showing on the sidebar as connected, but when I change the selection the value doesn't change.  I've checked the selection and the value by hand, and the connection is showing on the sidebar, but no change.  I was attempting to save the world to show this when I hit the no-save bug (see last issue)

**Comment by merryman** [comment]
Can you please give more details on what kind of HTML list and selection property you are using? I am not sure I understand exactly what you mean. Regarding the other bug you filed, it appears the connection does seem to do something, which is setting the textString of the target to null or undefined, which causes your world to error on save. We should do some type checking on behalf of the text morphs to prevent these kinds of value induced crashes.
