### ISSUE TITLE
Deprecate the lively.user system against one that authenticates against GitHub

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#541]
- [x] one should be able to log into lively with ones github account
- [x] this should enable a user to push/pull repositories
- [x] ~~not being logged in results in the same experience as being offline~~
- [x] the login can stay in the top right corner

# Research

- The POST endpoint of Github does not support CORS (known Issue), which means we either need to add a subserver or just use curl
- `curl -X POST -F 'client_id=d523a69022b9ef6be515' -F 'scope=repo' https://github.com/login/device/code` 
- curl -X POST -F 'client_id=d523a69022b9ef6be515' -F 'device_code=XXXX' -F 'grant_type=urn:ietf:params:oauth:grant-type:device_code' https://github.com/login/oauth/access_token
- With an access token we can use 
```
curl \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer XXXXX" \
  https://api.github.com/user
```
- to check whether we are logged in or not. We can use the `avatar_url` field of the response to display the github profile picture. 
- git clone https://XXX@github.com/user/repo.git -> might work with pull as well

**Comment by rickmcgeer** [comment]
@linusha @merryman we're planning to embed lively.next into Galyleo, and we have an authentication-by-github option.  We'd love to help with this.  Can we discuss this with @m-hemmings ?
