### ISSUE TITLE
Too easy to accidentally overwrite a system method in lively

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#55]
I've spent a fair chunk of today (in engageLively) dealing with a bug that crashed engageLively (forced it into a silent infinite loop).  It was because I'd accidentally chosen a name that was the same as one of the core system names.  I get that we don't get to namespace partition, but there really needs to be documentation/warnings that the user is doing this.

**Comment by merryman** [comment]
Can you please give more details on what exactly you have overridden?
At any rate, I think indicating via visual feedback that a certain method is overridden or not within the object editor is helpful. That way the user can immediately confirm if that is what they have intended to do or not.

**Comment by rickmcgeer** [comment]
I overrode render().  Of course, I should have known better; it was a boneheaded thing to do.

**Comment by merryman** [comment]
The Object Editor now warns on certain methods, if they are about to be overridden: f37d55d
 Also any overridden method now has a visual indication in the class tree on the left hand side.
