### ISSUE TITLE
Need to be able to browse configurations...

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#568]
I'm currently trying to track down a morph that's laying out badly.  The problem is that the morph in question is simply an instance of class Morph, and the problem is the layout configuration is bad.  Even if I figure out the right layout configuration from the tools, I then have the problem of finding the configuration in a large code base, and there isn't any obvious place to look for configurations.  We can browse code, but not configurations in the toolset.

**Comment by linusha** [comment]
What do you refer to as configuration? A component definition?
If that is the case - agreed. And bringing back the option to jump to a component definition via the halo of a component is on the roadmap. This is something that worked in the past, when there still were the snapshots based master components.

![image](https://user-images.githubusercontent.com/14252419/203954681-66ab936a-043a-4b2d-b854-17b607c5ab6b.png)

In case this is not what you meant, I would need further explanations, sorry.
