### ISSUE TITLE
Recipe for tying DOM Events to Morphs not working

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#58]
See: https://matt.engagelively.com/worlds/load?name=FirstTestWorld.  The list morph has html string:
```
<select onchange="$world.getMorphWithId('undefined_130DB726_E044_47C6_9A7C_F3DE60979D17').onSelectionChange(evt)">
<option value="3">3</option>
<option value="4">4</option>
<option value="5">5</option>
</select>
```
and onSelectionChange changes the color of an ellipse, and this was tested directly, but changing the selection doesn't change the fill. 
Two other tests were run: <select onchange="evt => alert('called');"> doesn't work, so evidently ECMAScript isn't supported, and <select onchange="alert('called');"> does.

**Comment by merryman** [comment]
I updated the world that fixes this issue.
