### ISSUE TITLE
Extending InputLine

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#583]
This may be a dead issue, since looking at the InputLine code I see there's an idea to move to native HTML inputs, but just so you know.  I've got an InputLine derived from InputLineDefault which takes an URL as input.  What I'd like to do is check that the entry really is an URL.  I'm doing this now in the code that uses the input, but it would be really handy to do this in the input line itself.  My current idea is to override the `onBlur()`  function to do the rewrite, with code that looks like this:

```
onBlur(evt) {
  super.onBlur(evt);
  try {
    const result = new URL(this.textString);
    this.input = result.textString();
   return;
  } catch (error) {
    this.indicateError('Please enter a valid URL');
  }
}
```
is this the right way to do it?
```
$world.execCommand("open browser", {moduleName: "text/input-line.js", packageName: "lively.morphic", });
```

**Comment by linusha** [comment]
This would be a possible solution, however, overwriting or otherwise hooking into `onInput` would be the better option in this case I think. This method is called once one confirms the input via pressing the enter key.
