### ISSUE TITLE
No way to edit components easily

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#589]
I think this will either be fixed with a visual component editor, or by coding practice.  
The issue is that the physical characteristics of a component are now in code,  and there isn't an easy way to navigate to the right file from the object.  The Object Editor icon brings up the code for the view, but the component is more than that; it's also the code for the physical arrangement of components.

A good example is in
```
$world.execCommand("open browser", {moduleName: "studio/helpers.cp.js", packageName: "galyleo-dashboard", });
```
The `BugReporter` is a `GalyleoWindow`, which is in a separate file.

Now, of course, I can manipulate the component with the properties panel or the inspector, but that just changes the instance of the component, not the component code itself.

I assume this is going to be fixed with better tooling.  For now, the workaround that I'm going to use in my own code is to trivially subclass the View code adjacent to the component, so the OE (well, the browser invoked from the OE) will take me to the right file.

**Comment by merryman** [comment]
Will be solved when the reconciliation, project management and component browser have landed. #528 #476 #530 #531
