### ISSUE TITLE
Need a transparent way to get ahold of the HTML element for a morph

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#591]
Some libraries (notably Chartjs) require the HTML element passed in for rendering. Specifically, the Chartjs code to draw a chart looks like:
```
const ctx = document.getElementById('myChart');
new Chart(ctx, <chart structure>)
```
I assume the Morphic equivalent is:
```
const ctx = document.getElementById(this.id)
```
but confirmation would be nice

**Comment by linusha** [comment]
I do not know if this would work right now, however, once the new renderer (#448) lands, just using the morph ID as the ID of the DOM node will not work.
What will work now and in the future is the following: `$world.env.renderer.getNodeForMorph(morph)`. You do not have to call this on `$world`. Any morph in the current environment should work, which basically means all morphs provide this reference. I recommend using $world for consistency.
