### ISSUE TITLE
Discussion re lightweight JavaScript/HTML5 engine/renderer

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#594]
I now have had two groups ask me about lightweight JS/HTML5 rendering outside of a browser context.  The issue is that the web UI platform is now easily the most advanced in the industry, and because of the network/platform effect it's getting even better and more popular.  However, as we all know, the browser (and many PWAs) are pigs.  If a JS-based 2DUI is combined with a 3D game/render engine (for example), embedding in a browser will bring the client to its knees.  I've also noticed high memory usage in web-based apps (e.g., Slack, Discord, Spotify).
My guess is that there's a pretty substantial market for a lightweight JS/HTML5 renderer (given how many libraries tend to rely on at least SOME HTML and CSS, we can't get rid of them all).  Any thoughts on this?

**Comment by merryman** [comment]
I don't understand what HTML5/JS without browser really means here. To my knowledge the majority of the runtime overhead the browser takes up is exactly **due** to those parts. If it weren't for HTML5/JS the browser would not be the memory hog to begin with. As far as just having the HTML5/JS bit without the rest of the browser that is pretty much what electron/nwjs already bring to the table. @linusha maybe I am missing something here?

**Comment by linusha** [comment]
I agree, the bulk of what a browser brings to the table is exactly the HTML/CSS/Rendering Engine.

I am not absolutely sure what you are proposing, @rickmcgeer, but the moment one wants to use HTML and CSS in a standard conform way, building such an engine from scratch is basically of the table and even if one would be successful, the probability that Chrome is not faster is slim I'd think.

By the way, VS Code is also based on Electron (= web based) and quite performant, many of these slower Apps like Slack etc. are just not as optimized on speed/low memory usage as they maybe could be, I'd guess.

All in all, there might be a market and it might even be possible to build such a thing, although I am skeptic. Even then, this has not really anything to do with lively.
