### ISSUE TITLE
ListMorph accept buttons appear off-screen

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#607]
![screen-bug](https://user-images.githubusercontent.com/656259/211110712-4d722bbe-9a37-4a23-9232-8d6ef492794f.png)

It's reasonably easy to work around (Halo, move) but it's annoying...

**Comment by linusha** [comment]
Could you point me to the lively commit you are currently using?

**Comment by linusha** [comment]
The same problem can be created with drop-down menus and tooltips (via the properties panel is probably the easiest way).
