### ISSUE TITLE
Opening an already open window should bring it to the front

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#61]
When opening e.g. an Inspector through the corresponding halo that is already open, the inspector is centered in the visible world right now. I think it would be nice if it would also get brought to the front. Right now, when working with a lot of open windows, it seems like a click on the halo does not do anything until one manually searches through the open windows.

**Comment by merryman** [comment]
This is specific to the inspector I guess. Fixed in: 5b8652a
