### ISSUE TITLE
Window Switcher lets windows grow indefinetly

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#620]
https://user-images.githubusercontent.com/14252419/211862978-c982ae1c-7838-49c9-b369-6cdbbdcd64d9.mp4

Additionally, windows never get unblurred.

**Comment by merryman** [comment]
We should maybe combine the fix of this with a completely new approach to window management. I believe an expose like solution would be quite nice to have: 
![mission-control-tips](https://user-images.githubusercontent.com/1296388/212108022-48a263a0-70dd-4c79-9056-ba84507249a3.jpg)
