### ISSUE TITLE
Commands requiring document crash when invoked on non selectable/document-free text morphs

### ISSUE THREAD

**Issue by merryman** [LivelyKernel/lively.next#627]
As part of our unification of Label and Text there are now a bunch of Text morphs in the system that are unable to support the operations required by several commands that ship with text morphs by default.
One of these is for instance the ability to navigate the cursor via the arrow keys. But there are certainly others I have not yet checked. Solving this basically requires either: (1) Weeding out all the critical commands and making them aware not every text morph is configured to support them or (2) developing a mechanism that filters the set of commands for a text based on the document/text layout being present or not.

**Comment by linusha** [comment]
We do 2.
