### ISSUE TITLE
Failed to create account

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#64]
I started from the login dialog, went to create account.  Filled in the form.  No response on the save button, and an error message popped up on the console:
![image](https://user-images.githubusercontent.com/656259/98442336-ce2c1980-20b8-11eb-813a-fac80c464daa.png)

**Comment by rickmcgeer** [comment]
I also tried from the button at the top left (chose "Create account" instead of "Sign in", with the same result.  Both of these were on the world at https://matt.engageLively.com/dashboard

**Comment by linusha** [comment]
Registering with a lively server will be deprecated soon, in favor of using Github OAuth (see #541).
