### ISSUE TITLE
The shape menu should have a video morph

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#645]
This could easily be done by the user today with an HTML Morph (and I imagine that's what the implementation will be) but this is a nice convenience.  Videos are ubiquitous these days, and the ability to control videos from Lively elements is very powerful.  I don't know how high-priority you want to make this, but users would appreciate it

**Comment by linusha** [comment]
I do not think, that we will implement and ship a VideoMorph with lively.next.
Our focus is on providing a stable platform/development toolkit, and less on providing a large collection of default components.

However
a) we are thinking about bringing back something like the old PartsBin, in which a VideoMorph could be provided, given someone implements it (and I agree with you, that should be quite simple with an HTML Morph and some library)
b) you can add custom morphs to shape menu already, the topbar provides a function `registerCustomShape` that you can use for that.
