### ISSUE TITLE
Responsive Design Halo

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#655]
The responsive design halo allows to add/remove breakpoints and also apply different masters depending on the breakpoint matching.

**Comment by rickmcgeer** [comment]
Can I learn more about this?  We would love to have responsive dashboards.

**Comment by merryman** [comment]
This is just a reminder ticket for the implementation of the responsive design halo.
We are planning to implement it via a breakpoint based master component switching mechanism.
Concretely, this means the user defines certain width/height ranges and for these ranges defines a particular master component that is applied to the composition that is supposed to be "responsive".
Building a good interface for defining these ranges is quite easily done, there are numerous examples online.
What will be a bit tricky is figuring out how the user can easily define the different components for the different viewport sizes without getting confused. There should be a good scheme for organising these viewport components and easily switching between them.
