### ISSUE TITLE
Should Popups block their "parent" controls in property panel?

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#658]
![color-picker-inconsistent-state](https://user-images.githubusercontent.com/14252419/214670799-377e1c3c-6097-4be0-9873-b48417e7631a.gif)

As can be seen, it is currently possible to create inconsistent state with the color picker opened. This might very well apply to other widgets/properties as well.
I see two options to tackle this:

1. We block the color editor in the properties panel as long as the color picker is open.
2. We hook them up bidirectional (changing the value in the color picker will update the properties panel).

**Comment by merryman** [comment]
I would like to suggest option 3: Just close the popup when the user starts to interact with the parent input again. This is also what Figma does.
