### ISSUE TITLE
Versioning Indicator

### ISSUE THREAD

**Issue by SilvanVerhoeven** [LivelyKernel/lively.next#66]
In Lively.next, some files are serialized and versioned in the Morphic DB, the others are versioned via Git. It would be good to have a simple yet obvious indicator showing whether a file is versioned via Git (hence needs to be handled differently than just by saving the world).

**Comment by linusha** [comment]
![image](https://user-images.githubusercontent.com/14252419/194607378-b532eba6-446b-4883-8753-3a6045cb81cf.png)
