### ISSUE TITLE
Connections and bindings are still very opaque and hard to debug

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#677]
And, frankly, they shouldn't be.   I'm having the following issue.  In a `Morph` class, I have methods to handle button press signals on submorphs, and so I try, in `get properties()`
```
   bindings: {
     get() {
         return [
               {model: 'start button', signal: 'fire', handler: 'startMoving'}
         ]
     }
   }
```
OK, so I try this old-style code in the Morph's `onLoad()` method (after `whenRendered()`):
```
    if (this.getSubmorphNamed('start button')} {
       connect(this.getSubmorphNamed('start button'), 'fire', this, 'startMoving');
    }
```
And when I press the button, nothing.  When I invoke `startMoving` manually, it works fine; when I hand execute the `connect` method there are no errors, but still nothing happens when I press the button.  And there's just no way to inspect the state (what _should_ be called when I press the button?).  Or, at least, I haven't found one.

**Comment by rickmcgeer** [comment]
I figured it out, by attaching the bindings to the appropriate model, so this is closable.  That said, I'll leave it open as a request for enhancement (I really would like this to be more transparent)

**Comment by linusha** [comment]
Yes, you are right and we are very open to concrete ideas on how to make connections more accessible. However, this is already filed in #163 imo.

---

Just to make sure: The bindings property will **only work on classes that extend `ViewModel`**. Thus, this shortcut to create connections is only available for components.
Additionally, even with `ViewModel`, `{model: 'start button', signal: 'fire', handler: 'startMoving'}` and   `connect(this.getSubmorphNamed('start button'), 'fire', this, 'startMoving');` do different things. In `bindings` you can either find a submorphs by its name (via `target`) or target it by the `ViewModel` that the submorph has. This is what `model` does.
