### ISSUE TITLE
Component doesn't have isComponentDescriptor or isPolicy set in frozen version

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#679]
As a result, `part` is returning undefined.  It works fine in the studio, and I checked and `isComponentDescriptor` is `true` in the studio, but on the frozen page it is undefined.  
The repo is https://github.com/engageLively/gravity-game
The component is instantiated in `main`: 
```
$world.execCommand("open browser", {moduleName: "index.js", packageName: "gravity-game", codeEntity: "main"});
```
The frozen version is at  https://matt.engagelively.com/users/rick/published/gravity-game/index.html

I traced the error using the debugger.  The relevant call to `part` is at line 16674 of `index-a7dbfcdc.js` and reads::
```
 game = __varRecorder__.part(__varRecorder__.GravityGame);
 $world.addMorph(game);
 game.viewModel.init();
```

I thought it might have been a timing issue, but

- `part` isn't asynch
- adding an `await` had no effect.

I checked in the editor and `game.isComponentDescriptor` was `true`.  In the console debugger in the frozen version, it was `false`

**Comment by merryman** [comment]
This is because your `gravity-game` is using projects as 3rd part dependencies. As previously mentioned in #681 this is not yet supported but will be in the near future. It will then solve the issue you are describing as well.
