### ISSUE TITLE
Error when click component button in new project

### ISSUE THREAD

**Issue by kholbekj** [LivelyKernel/lively.next#689]
Error in interactive command browse and load component: TypeError: Cannot read properties of undefined (reading 'isCo...
TypeError: Cannot read properties of undefined (reading 'isComponentDescriptor')
    at Window.part (http://localhost:9011/lively.morphic/components/core.js:15:29)
    at Object.exec (http://localhost:9011/lively.ide/world-commands.js:1006:111)

**Comment by merryman** [comment]
We are still working on implementing that feature. It is part of #476.

**Comment by kholbekj** [comment]
Maybe a fun little thing for me to try to figure out how to do could be a nice "not implemented yet" warning? :) Always good to be able to distinguish expected failure from unexpected!

**Comment by merryman** [comment]
You are welcome! We do have some parts in the code where we use a `nyi()` call. 
Take look at: `$world.execCommand("open browser", {moduleName: "src/resource.js", packageName: "lively.resources" });`
But we have not real consistent handling of this sort of thing in the system.

**Comment by linusha** [comment]
Since the `nyi` PR is not really related to the fact that the component browser is missing at this time, I'll close here for now.
