### ISSUE TITLE
I managed to make the JavaScript window go away and then couldn't restore it

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#69]
![image](https://user-images.githubusercontent.com/656259/98749373-5d168b80-2370-11eb-9347-762b7c2c3658.png)

**Comment by merryman** [comment]
From the looks of this, I think you managed to crash the rendering process by #67. This already caused issues in #68 which is basically the rendering engine not being able to reconcile the dom any more. This looks like another instance of that.
