### ISSUE TITLE
Fast Load should be the default

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#7]
Most people don't use the functionality in full load and don't need it.
![image](https://user-images.githubusercontent.com/656259/96063126-16ef0a80-0e4c-11eb-92f1-d1ad8208001c.png)

**Comment by merryman** [comment]
I do agree. However next week I will be releasing the improved default load where we completely skip fetching the sources from files if already cached. That should lead to a quite significant speedup which may make this mode not so crucial any more.

**Comment by merryman** [comment]
@rickmcgeer please update to the latest version of lively, clean your browser and load worlds a couple of times. The second time you load the "slow" load should now see significant speedup. If you still think you prefer "fast load" let me know.

**Comment by linusha** [comment]
Currently, this button provides no functionality anyways. In the future, we will try to utilize dynamic loading of modified content only, and loading unmodified core modules only from the bundle. This will hopefully speed up the loading times of lively.next. The fast-load toggle will go.
