### ISSUE TITLE
Clicking on Font Family on Styling sidebar brings up login prompt

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#70]
![image](https://user-images.githubusercontent.com/656259/98751273-a8329d80-2374-11eb-893e-d207072dce3c.png)

**Comment by rickmcgeer** [comment]
And after it's clicked away, the register overlay remains
![image](https://user-images.githubusercontent.com/656259/98751410-e203a400-2374-11eb-90e9-ed5ce42dde65.png)

**Comment by merryman** [comment]
Thank you, I will look into this.

**Comment by merryman** [comment]
Should be fixed now in: bab6d0f6fc4ed4a732945b7c200f9024623fc867
