### ISSUE TITLE
Accepts Drops in Menu

### ISSUE THREAD

**Issue by Paula-Kli** [LivelyKernel/lively.next#72]
When using the morph menu in the upper left corner and selecting the Morphic property `acceptsDrops` as shown below the morph still accepts drops.
![screenshot1](https://user-images.githubusercontent.com/49535291/98797124-740abb80-240c-11eb-8e7b-a35378e61680.png)

Nevertheless after that you get a lot of error messages when trying to drop something in the respective morph. In addtion to that after disabling `acceptsDrops` the menu is broken.
![screenshot1](https://user-images.githubusercontent.com/49535291/98798205-e5973980-240d-11eb-9a38-a7938d7cee71.png)

What is the intended meaning of this button and menu?

**Comment by merryman** [comment]
Thank you! Fixed now in 4796062. And it should now work the way you expected it to :-)
