### ISSUE TITLE
Freezes are failing

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#720]
It's not clear if this is an issue with Galyleo Dashboard or with the freezer:
https://github.com/engageLively/galyleo-dashboard/issues/161

Note that I'm on the updated version of lively.next (pulled this morning) and the node version is 19.6

Running native on Windows

**Comment by merryman** [comment]
We do not support node 19. We can add a check for that into the freezer which will fail more gracefully. But it wont change the fact that we do not support building on nodejs 19 for the time being.
