### ISSUE TITLE
LoadingIndicator is not always visible in loading screen

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#725]
As the title states, the loading indicator is often not visible. This is not always the case. I believe it is always missing when one loads lively in a given tab for the first time. Subsequent loads in the **same tab** will have the loading indicator.
We should fix this, as it is sometimes hard to grasp if one is stuck in the loading screen or if it just takes a while.

**Comment by merryman** [comment]
I think it is only missing when you load a new project via `http://localhost:9011/worlds/load?name=__newWorld__`. If I load an existing world It works reliably.

**Comment by linusha** [comment]
> I think it is only missing when you load a new project via `http://localhost:9011/worlds/load?name=__newWorld__`. If I load an existing world It works reliably.

I'll check if loading an existing project helps for me as well.
The observation with the tab above holds for new worlds for me.
