### ISSUE TITLE
Scene graph tab going away

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#735]
I tried to get rid of the scene graph, and this happened...

![scene-graph-bug](https://user-images.githubusercontent.com/656259/222936545-1b55b8f9-68c7-46f2-a3da-7541ab49f382.png)

Unfortunately, I've been unable to reproduce...

**Comment by linusha** [comment]
I occurred this situation as well this week, but thought I had somehow deleted it. I will try to reproduce it.
