### ISSUE TITLE
Settings file for mutliple-deployed worlds

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#737]
This isn't a feature request so much as a request for guidance on best practices.  We're going to run into a situation where we want to deploy the same application, but with local settings -- e.g., tokens to pass to a third-party server, etc.  The obvious place to put the local settings is in a file like `settings.js` and import that, but guidance on best practices/conventions with the freezer would be very helpful.  Add this to the build script?

**Comment by merryman** [comment]
I think we should move this discussion into the your project repo. We do not have an opinion on how to manage different build targets in lively.next, and are not planning to do so in the near future.
