### ISSUE TITLE
Request about component architecture implementation of components with a variable number of submorphs

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#747]
**What would you like to achieve?**
I want to create a component that has a list of subcomponents.  Each subcomponent has a couple of buttons, and the buttons should call back to methods on the owner

**How are you trying to achieve that**
Back in the old days, I'd've had a class like this:
```
class SubComponentMorph extends Morph {
    init(objectWithInfo, callbackTarget) {
         // set stuff up
   }
  buttonAction() {
       this.callbackTarget.subcomponentButtonPressed(this);
  }
 ...
}

/* And then, a class for the container which contained them */

class ContainingComponent extends Morph {
      init(arrayOfObjects) {
          const containedMorphs = arrayOfObjects.map(obj => {
                const contained = new SubComponentMorph();
                contained.init(obj, this);
                return contained;
          }
         containedMorphs.forEach(morph => this.addMorph(morph));
      }
      subcomponentPressed(morph)  {
          // do whatever
     }
}
```

But now I'm not entirely sure what to do.  A component seems to be a static variable, with a fixed number of submorphs.  So should this be put in a morph, and the morph instantiated in a component?   
         

**Alternative solutions**
If applicable, what other solutions have you tried?

**Additional Resources**
Please provide links to any custom code that might be necessary to grasp your problem. Screenshots of custom component, etc. are also appreciated. 

**Version**: Please paste the lively.next commit on which the problem occurred here (short version from the Version Checker in the bottom left corner is sufficient).

**Comment by merryman** [comment]
I dont think there is much that keeps you from following the above approach while using components as a basis.
You see, the static definition of a master component should more be thought of as a "start configuration" of the morph structure. So once you instantiate the a morph from the component,  you are free to modify parts of the morph however you like. Keep in mind that when you perform dynamic modification you have to manage all of the connection logic on your own, but glancing at your above example you already have a solution for that.
