### ISSUE TITLE
Add line numbers to browser

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#749]
**Describe the Feature**
Error messages in lively always reference the line number, e.g. `at Window.makeRequest (http://127.0.0.1:9011/lively.resources/src/http-resource.js:83:12)`. In fact, this also happens in error messages and cautions when a save is done in the browser.  
Unfortunately, the browser doesn't display line numbers, which means hunting for the error is something of a problem.
**Graphics**
![Screenshot 2023-03-07 184746](https://user-images.githubusercontent.com/656259/223607016-07f142d4-c80f-442a-a426-fd0830c57072.png)

**Implementation Details**
I know this may be more complex than it appears.  In particular, the line numbers in the browser don't appear to line up with any plausible location of the error message, so there's something (transcription?) that may be screwing up the correlation.  But this is a killer when we start to get users.  It's just too obvious a thing.

**Comment by merryman** [comment]
Thank you! This is already covered by #378 and we are working on it, so I will close this.
