### ISSUE TITLE
Halos remain on the screen, even when the Haloed morph is removed

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#756]
**Describe the bug**
The subject line has it -- multiple halos remain on the screen, and can't be removed.

**To Reproduce**
This happens episodically.  It must be some strange combination of keystrokes, but unfortunately I haven't been able to isolate it

**Screenshots**

![Screenshot 2023-03-08 210457](https://user-images.githubusercontent.com/656259/223925876-ba6559ab-80dd-4744-8684-5adbc036f9ee.png)

**Setup**
Please check the applicable boxes:
- [ ] macOS 
- [ ] Linux
- [X] Docker
- [X] Windows

**Version**: Please paste the lively.next commit on which the problem occurred here (short version from the Version Checker in the bottom left corner is sufficient).
 0e22dbdb9416630eaf14c02b4da607af029b508d

**Comment by linusha** [comment]
As per @merryman: We are quite sure this is not a general lively issue.
Thus, I'll close this.
