### ISSUE TITLE
Robust loading when there are errors in `localconfig.js`

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#774]
**Describe the Feature**
This is related to #773 -- a bad line in `localconfig.js` stopped the world from loading.  The problem with world-loading failures is that it's very difficult for a typical user to trace the error and remedy it (I know, I got it in a few minutes, but I'm pretty experienced with this system).

This is overall an issue with lively -- there are lots of things  (missing NPM files, bad config files, etc) which prevent worlds from loading, and this really leaves a user stuck.

**Implementation Details**
Triage the files we need to have into must-haves, should-haves  and nice-to-haves.  We put the must-haves into a "Safe Mode" bucket, and use our own local caches to ensure that they _always_ load, so the user will _always_ get a functioning lively world.  This is equivalent to the old boot-to-safe-mode on PCs and Macs.   The should-haves we try repeatedly (I know @merryman is working on this).  The nice-to-haves, if they have an error, just get thrown on the floor.  `localconfig.js` is the prime example.

**Comment by merryman** [comment]
The error handling of cases where crashes in the localconfig occur is already present. What caused the issue you are describing is a bug in our error printing, which ironically crashed the world load. This should be fixed in #963.
