### ISSUE TITLE
Status Text button in browser have wrong state upon opening the browser

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#781]
**Describe the bug**
The export markdown to HTML button is visible upon opening the system browser, although the loaded module is a JS one.

**To Reproduce**
Open the browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/14252419/226635719-8bef1501-1355-4df4-9167-f304f86a5746.png)

**Setup**
Please delete non-applicable items!

- Linux

**Version**: 0be75836ad1b81aec5f6555e71f651bd683722c5

**Comment by merryman** [comment]
This bug has been fixed in #816.
