### ISSUE TITLE
Styling of selected tree items is off when they are too small

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#784]
**Describe the bug**
Starting at smaller windows, folders with long names that are selected in the file browser will show a large white rectangle instead of legible text. 

**Screenshots**

https://user-images.githubusercontent.com/14252419/226669523-4090cbd5-a5d0-4c81-8b96-804cd21cf4c6.mp4

**Setup**
- Linux

**Version**: 0be75836ad1b81aec5f6555e71f651bd683722c5

**Comment by merryman** [comment]
This appears to be fixed mostly. There is still an issue with the date and the name of the folder not aligning exactly, when the space is really tight, but that has been always the case here. Selection wise this was likely fixed by #1001.
