### ISSUE TITLE
connection still not working on input

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#80]
See https://matt.engagelively.com/worlds/load?name=dataParser.  The input property of morph entry is connected to the processInputCharacters() method of headerSpecifier.  But when I enter text it doesn't automatically get invoked, even when I hit return.  I've run the method from the object editor, and it's working fine.
This may be a documentation/usage issue -- am I connecting to the wrong property?

**Comment by rickmcgeer** [comment]
Now I have connected the fire method of a button to processInputCharacters, and I am getting a different error: a "Cannot read property getSubmorphNamed of null".  But this is in the method processInputCharacters, and when I invoke from the Object Editor it works well.  Further, the only reference to getSubmorphNamed is this, so presumably this is null.
![image](https://user-images.githubusercontent.com/656259/98854425-660a6a00-240f-11eb-99f8-4a5574e2dd46.png)

**Comment by merryman** [comment]
The events you should be listening for is `inputAccepted` (on enter) and `inputChanged` (on typing);

**Comment by rickmcgeer** [comment]
Just tried inputChanged, and that didn't work, either.
