### ISSUE TITLE
Video Morph requested

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#807]
**Describe the Feature**
Playing videos is now an important part of web applications, and Lively should be able to offer _really cool_ functionality here -- e.g, embedding Morphs in videos and making them respond at specific time points in the videos, or have them control the videos in response to user events.  I could see Lively being a vital tool for the TikTok generation. _Nobody does this well_, and it would be _easy_ for us.

Right now, I'm embedding videos with an `HTMLMorph`, using HTML code like this:
```
\`<div style="display: flex;
            align-items: center;
            justify-content: center;
            height: 100%;
            ">
  <video id=${this.videoID} width="${this.width}" height="${this.height}">
  <source src=${this.videoUrl} type=${this.videoType}>
Your browser does not support the video tag.
</video>
</div>\`
```

Which works, but it's somewhat clunky.  The really difficult thing is that in order to control and interact with the video, which requires getting a handle on the video dom element.  I'm currently doing it like this:

```
get videoDomElement () {
  return this.domNode.querySelectorAll('video')[0];
}
```

It's not clear to me that this is robust.

**Implementation Details**

I would be happy to take a cut at the first version of the implementation, which would be very simple -- really just the HTML code above, exposing the `videoDomElement` as above, and writing convenience methods to play, sense video events, etc.  The actual HTML code would need to be more complex, adding (for example) the play speed and the various boolean attributes (`loop`, `autoplay`, etc)

Before I start in, any guidance would be appreciated -- and also, where this should go in the lively code.

**Comment by linusha** [comment]
We would appreciate any contributions in that regard! 

The node referencing has been already covered in #808. As for where to put this, I think just a new file `video.js` inside of `lively.components` is fine.

You might want to utilize a third-party library such as [videojs](https://github.com/videojs/video.js) or [plyr](https://github.com/sampotts/plyr). You can import them into lively with `import videojs from 'esm://cache/video.js'` or `import Plyr from 'esm://cache/plyr'` respectively.

If you need anything more or need a review, just ping me here! Looking forward to it! :)

**Comment by rickmcgeer** [comment]
I've written a `VideoMorph` and have it locally.  I've got this in a separate branch, but when I attempt a push I'm getting this error:
$ git push --set-upstream origin video-morph
ERROR: Permission to LivelyKernel/lively.next.git denied to rickmcgeer.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Can you guys give me access to the repo?  I promise I'll only push to non-main branches.

**Comment by linusha** [comment]
@rickmcgeer I sent you an invite.
By the way, in general it is possible to contribute to open source repos without the necessity of actually being invited by doing the following:
1. Fork the repository, so that you have your "own copy" of it
2. Make the changes inside of the fork where you have all the rights
3. You can then create pull requests from a branch in the fork to a branch in this repository.

However, just accepting the invite should be enough for now, I wanted to spare you the stress of setting up new remote branches etc.
