### ISSUE TITLE
Best practices for integrating native HTML Libraries

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#808]
**What would you like to achieve?**
Many HTML libraries require the programmer to work through the DOM API.  I've most recently run into this in implementing videos (see #807), but I've also seen this in [ChartJS](https://www.chartjs.org/) (see, for example, the sample in [ChartJS Sample](https://www.chartjs.org/docs/latest/getting-started/usage.html)).    HTML Morphs are common ways to work with these libraries, but then the problem is getting the actual DOM Node to manipulate.  However, lively tends to wrap extra `<div>` elements around the actual element that we want to get at.

**How are you trying to achieve that**
Currently, I'm using the `this.domNode` attribute, and using the  `querySelectorAll` method with tags.  For example,
```
get videoDomElement () {
   return this.domNode.querySelectorAll('video')[0];
}
```
Which is fine, but I'm not sure this is the most robust solution for the problem.

The key is that if we can robustly expose the relevant DOM node for a library call, people can immediately use the native HTML5 methods, giving us both free implementations _and_ documentation.

**Version**:
54e8e6aff13c2dd56f95ea89ccb1d5b129766394

**Comment by linusha** [comment]
> However, lively tends to wrap extra `<div>` elements around the actual element that we want to get at.

Although in general you are right, the structures generated by the renderer tend to be quite complex, this is not the case inside of the `HTMLMorph`. Here, starting from the `domNode` of the `HTMLMorph` downwards, lively will not interfere with whatever structure you build in there.

The approach you outlined is fine! Here are a few points for thought:

1. `querySelector()` will probably always be the better choice over `querySelectorAll()[0]`.
2. DOM operations are quite costly. I would recommend selecting the node one time, and then storing a reference to that, i.e., not querying every time the getter is called.
3. Often, libraries will also return the relevant node for you, if that is applicable (unfortunately did not seem so for `ChartJS`) just storing that reference is probably the easiest way.
