### ISSUE TITLE
`addEventListener` syntactic/semantic sugar on signals

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#809]
**Describe the Feature**
The issue is that there's a standard way in HTML/JavaScript for UI elements to interact: the `eventListener` paradigm.  It's ubiquitous.  However, Lively uses an interaction paradigm that is, on the surface, different -- `signal`.  Objects emit signals and listeners bind handlers to the signals (the [Luimino](https://lumino.readthedocs.io/en/1.x/api/) widgets do something similar to Lively).

The problem I keep running into is that it's not clear what to bind to, and when nothing happens it's not clear why.  Is the signal emitted by the `Component` or `ViewModel` or `Morph`?  How do I find out?  And when nothing happens, where do I check to see why?  Did the signal not get emitted?  Did I bind it wrong?  Etc...

The common practice with other libraries, including HTML itself, is to add an event listener to a pair (object, event).  The object will typically expose its list of event listeners for each event.

This seems very similar to what Lively does -- an event is just a signal, binding a handler is just adding an event listener.  All I'd really like is an interface similar to what HTML5, ChartJS, etc do natively, so the use pattern is similar and more explicit. 

**Implementation Details**

If the implementation isn't dirt simple, mostly a few lines per signal in `Morph`, `Component` and `ViewModel`, this isn't worth doing.  The idea is just to give an `eventListener` interface on the existing `signal` architecture

**Comment by rickmcgeer** [comment]
So I've been thinking about an implementation of this, on the `Button` ViewModel and associated components.  See: 
```
$world.execCommand("open browser", {moduleName: "buttons.js", packageName: "lively.components", codeEntity: "ButtonModel"});
```
So the thought is to expose a method:
```
addEventListener(eventName, handler) {
  if (this.listeners[eventName]) {
    this.listeners[eventName].push(handler);
  } else {
    this.listeners[eventName] = [handler]
  }
}
```
Of course, the events that make sense have to be exposed, so we add the following property:
```
get events() {
  return ['fire']
}
```
And then invoking the handlers:
```
onFire() {
  this.listeners.fire.forEach(handler => handler())
```
And then we have to tie the `onFire()` method to the `fire` signal:
```
{ signal: 'fire', handler: 'onFire' }
```

**Comment by merryman** [comment]
Most of what you describe can already be achieved by `lively.bindings`. You can find a relatively comprehensive documentation of the API here: https://github.com/LivelyKernel/lively.next/wiki/Bindings,-Connections-and-Signals.

That being said, you are right that we are lacking in terms of support for event handling in general when developing inside lively. There is no insight for the developer what to bind to (Neither in code nor in the visual domain). And both sides could be improved. Code wise, we could think about migrating code to TypeScript and see how that would work in tandem with a live programming approach. However we could also look into what kind of magic LLMs could provide us with here, if we were to specialize one for lively.next source code base. In terms of visual interface, we have had multiple different attempts at a fabrik like interface that scales in the past and building a decent one is still on our bucket list. However that is still some time down the road for us for now.

**Comment by linusha** [comment]
This is consumed by #1389.
