### ISSUE TITLE
Morph fills shouldn't be the same color as the background

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#81]
The background should by default be a different color from morphs, otherwise a new morph just selected is invisible when not selected.

**Comment by merryman** [comment]
In fact they are transparent. I will think of a better default color.

**Comment by linusha** [comment]
I will close this, as there are good reasons to stick with transparent. Most importantly, this is how similar tools, e.g., figma, do it.
"Finding" "accidentally created" morphs (or purposefully created ones, for that matter) should be the responsibility of the scene graph. If it is insufficient for this task currently, this is the problem to tackle.
