### ISSUE TITLE
Initialization of properties

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#811]
**What would you like to achieve?**
I'd like to have a generic initialization for a property (and it may well exist, I just don't know it -- hence the support inquiry).    

**How are you trying to achieve that**
What I'm doing now is putting the property initialization code into the `onLoad()` method, and I'm pretty sure there are better ways to do it.

**Comment by merryman** [comment]
You can find a nice overview of controlling the order of property initialization here: https://github.com/LivelyKernel/lively.next/wiki/Morphic 
It also describes how to define initializers for different properties.

**Comment by linusha** [comment]
Until further notice, I consider this done. Feel free to reopen if I am mistaken.
