### ISSUE TITLE
Reintroduce loading bar animation on loading screen

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#812]
**Describe the Feature**
We rencently removed the animated loading bar from the loading screen for performance reasons. The result is a loading screen that looks very oldschool. It would be nice to reintroduce the animations.

**Implementation Details**
The reason for the animation being removed was, that our `morphic` Animations are implemented in a way that results in them running on the main thread. However, we can implement animations using `WebAnimations` and `CSS` in a manner that results in them running on the compositor thread while we are still able to control the progress of the animation in the main JS. After seeing how well this functions with the loading bar, we might be able to draw some additional conclusions on how a refactor of our animations library might look like to profit from this performance benefit at all times.

**Comment by merryman** [comment]
This will be handled by us re-designing the landing and loading page in general (removing the expensive 3d globe) and also a general refactoring of the animation engine in the renderer, such we are less likely to hog the main thread.
