### ISSUE TITLE
Finding dimensions of submorphs without `whenRendered()`

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#813]
**What would you like to achieve?**
My understanding (from the comment thread on #810) is that `whenRendered()` will be eliminated.  I use `whenRendered()` heavily,  since (AFAIK) it is only then that the extent of submorphs and available window size is known.  This is particularly important when doing responsive design, since at that point we need to resposition and rescale to accommodate the constraints of the window.  

So what I'd like to know is after what event and this repositioning should occur...

**Comment by linusha** [comment]
We will not remove this without warning and without providing guidance/new code for existing projects! 
The concrete implementation of `whenRendered()` is subpar and we are working towards a future in which we can make stronger guarantees about the rendering of morphs than currently. When/If we figure out how to achieve this, we will however probably add a similar hook function, like `onAfterRender()` or something similar.

**For now, this is nothing to stress about. You can keep using `whenRendered()` and we will provide a clear warning and guidance when things change. At the moment, there is no better alternative available.**
