### ISSUE TITLE
Morphic properties need to be adjusted on components and their submorphs

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#82]
- [ ] Text should not accept drops
- [ ] Submorphs on pre-done components should not accept drops or be draggable or grabbable, or have halosEnabled
- [ ] Buttons and other control widgets should not be layoutable

**Comment by merryman** [comment]
Thank you! Here are my thoughts:

1.) Embedding morphs inside texts is in fact a feature not a bug. You can always disable that by setting `acceptDrops = false` or via the morph menu.
2.) I disagree about the halo part. How am I going to override bits of the component, like change the font color? without halos that is just a mess. We can certainly agree on not accepting drops, but removing all inspectability goes too far.
3.) I almost always have buttons sitting in a layout. I never position them absolutely. I dont understand why they should be left out of the layout by default.
