### ISSUE TITLE
Failure under Docker on Windows

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#827]
**Describe the bug**
I'm experiencing a failure in Docker on Windows (WSL).  When I run Lively.next in a docker container `make docker-build`, accessing 127.0.0.1:9011 shows this error message in the browser
Update required
Everything works fine when I run native (`./start.sh`). However, I can't do a build native (wrong version of node on my box) so my procedure is to run native for my programming environment, quit, kill the server, then run a docker container and do an `npm run build` inside the docker container.  It works, but it's clunky.
I've tried rebooting (obviously) removing old containers and rebuilding...nothing works.  Since running native works fine, it's obviously some funny interaction between Windows, Docker, and Lively (well, probably node) but it's not clear what it is.  It does seem that it has to do with an http connection that should be upgraded to Websocket, but that's a guess.
I've tried on both Chrome and Edge.

**To Reproduce**
To be honest, I don't know how reproducible this is.  I do know that the 'Upgrade required' message is from node.js, and a look at developer tools shows me that the error code from the server is 426.  See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/426

**Screenshots**
![Screenshot 2023-04-27 205529](https://user-images.githubusercontent.com/656259/235050618-4a765693-4527-4701-8956-4d5b723291c1.png)
![Screenshot 2023-04-27 205641](https://user-images.githubusercontent.com/656259/235050733-e0b3cf17-de85-4822-ad99-5cac66225cc9.png)

Microsoft Edge is giving a slightly different error:
![Screenshot 2023-04-27 210314](https://user-images.githubusercontent.com/656259/235051438-4ecd295f-0ce2-46a4-aa3e-1d8c9d486cf3.png)

**Setup**
Please delete non-applicable items!

- Windows

- Docker

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).
aa0d36364ca608fb2c67ae2f2c34d670d1e0891d

**Comment by linusha** [comment]
@rickmcgeer we got ourselves a windows machine for testing purposes, so any specific pointers with regards to your setup (node versions, docker versions,...) are highly appreciated! We will then investigate this problem and try to resolve it!

**Comment by linusha** [comment]
Setup as reported in #849:

> I'm running node 19.6, ubuntu 20.04 LTS focal
> As for WSL:
> WSL version: 1.2.5.0
> Kernel version: 5.15.90.1
> WSLg version: 1.0.51
> MSRDC version: 1.2.3770
> Direct3D version: 1.608.2-61064218
> DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> Windows version: 10.0.22621.1702
> Docker version 20.10.22, build 3a2c30b
> Windows version 22H2 (OS Build 22621.1702), Windows 11 Home
