### ISSUE TITLE
Differing results on localhost and 127.0.0.1

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#849]
**Describe the bug**
http://127.0.0.1:9011/ works fine, but http://localhost:9011/ gives 'Upgrade Required'

No error messages on the server-side console

**To Reproduce**
Just open the two addresses

**Screenshots**
localhost:
![Screenshot 2023-05-19 114946](https://github.com/LivelyKernel/lively.next/assets/656259/05e8f012-fc3a-4eb0-bf3e-033ff83b64d2)
127.0.0.1:9011

**Setup**
Please delete non-applicable items!

- Windows

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).
332dfb39b76e86c0096a5d4737aa8e990d36a9b2

**Comment by rickmcgeer** [comment]
It does seem to be related to #827 and it could be a failure of windows networking.  OTOH, I'm running Croquet on 9684, and localhost:9684 and 127.0.0.1:9684 both work fine.
I'm running node 19.6, ubuntu 20.04 LTS focal
As for WSL:
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1702
Docker version 20.10.22, build 3a2c30b
Windows version 22H2 (OS Build 22621.1702), Windows 11 Home

**Comment by rickmcgeer** [comment]
Ah.  I killed Croquet and tried it again, and now it works.  So it's something local to Windows about running two servers on separate ports...

**Comment by linusha** [comment]
Alright, I'll close this one then and investigate #827 sometime with the reported setup, thanks!
