### ISSUE TITLE
Potential beta test for Reconciliation

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#850]
**What would you like to achieve?**
Since the lively upgrade, I haven't been using Projects at all; my typical workflow has been to do physical design by hand, then  copy the physical design parameters into a Morph spec.  However, I'm kicking off a joint project with @lin564, and it seems likely that using a Project-based workflow will be the best way for us to share information.  In particular, @lin564 will want to design by hand and preserve the designed world in a Project, and she'd like me to write code in that Project.
It occurs to me that with @merryman nearing completion of reconciliation, that this will be an excellent Beta test with a designer (@lin564) and coders (me and potentially @merryman ) working in the same project.

**Comment by linusha** [comment]
Hey @rickmcgeer and another warm welcome to @lin564!

First off - great initiative and we would of course very much like for tests like this to happen and are prepared to provide extensive support!

Let's clear up some terminology first: What you are referring to as _Projects_, @rickmcgeer, are still what we used to call worlds in lively.next, although @merryman and I started also calling them Playgrounds. The new reconciliation feature is independent of the mechanism that is used to preserve the progress of something that was build in lively.

**Comment by linusha** [comment]
Here is an overview on how to work with projects in our wiki: https://github.com/LivelyKernel/lively.next/wiki/Projects

**Comment by rickmcgeer** [comment]
@linusha this is exciting.  What version should I be running to do this on?

**Comment by rickmcgeer** [comment]
@linusha any recommendations for a Matrix client, etc?

**Comment by linusha** [comment]
> What version should I be running to do this on?
@rickmcgeer  This is not yet merged, but the PR is currently under review. I expect that we are able to merge this in the next days and will report back to you once this is done!

> any recommendations for a Matrix client, etc?
I strongly recommend using https://element.io/ also also just signing up over the wizard of element, which should just get you an account on the matrix.org instance I believe, which is fine.

> Incidentally, it's difficult to sign up for a Matrix account. Do you have a Discord or Slack option?
Not really. What specific problems do you occur?

**Comment by linusha** [comment]
Until further notice, I consider this done. Feel free to reopen if I am mistaken. Otherwise, we are excited to welcome you in the matrix chat and work things out! :tada:
