### ISSUE TITLE
Master states

### ISSUE THREAD

**Issue by merryman** [LivelyKernel/lively.next#855]
We want custom styling in response to runtime behavior to play nicely with styling via master components.
That means that we *do not* want to have custom style properties scattered around in our code that likely even override our master styling behavior. Instead we want to move those properties *into* the component definition themselves and then trigger these customizations when needed conveniently from code.

**Comment by merryman** [comment]
This is dealt with in the upcoming https://github.com/LivelyKernel/lively.next/tree/feature/responsive-design

**Comment by linusha** [comment]
By the way, @merryman, our wishlist for this feature from past autumn can be found in #536.
