### ISSUE TITLE
Pointer should change to match operation

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#86]
When I move the mouse to the side or corner of a window,  the mouse pointer remains an arrow; standard is it should change shape to show I can move the sides/corners to change the shape

**Comment by merryman** [comment]
That is a bug in the chrome debugger. After inspecting elements it sometimes causes all mouse cursors to be reset to auto for some reason. Can be fixed by opening the debugger, inspecting and element and then closing the debugger again.

**Comment by rickmcgeer** [comment]
Thanks
