### ISSUE TITLE
How do I adjust morph behavior on scroll?

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#867]
**What would you like to achieve?**
The Galyleo Dashboard Studio treats a mouse wheel scroll as a vertical drag, even when I disable dragging.  This happens even in deployment with the frozen part, which is obviously not desirable.  See the  attached screenshot.
![Screenshot 2023-05-31 173547](https://github.com/LivelyKernel/lively.next/assets/656259/a92ab028-ef60-4d55-809f-75be2a8b28c6)
So what I'd like to do is:

1. Disable mouse wheel movement
2. Disable dragging, grabbing, and halos on the Studio and all of its submorphs in deployment

Any thoughts on how I can do that?

**How are you trying to achieve that**

**Alternative solutions**
If applicable, what other solutions have you tried?

**Additional Resources**
Please provide links to any custom code that might be necessary to grasp your problem. Screenshots of custom component, etc. are also appreciated. 

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).

**Comment by merryman** [comment]
This can be achieved by disabling the `config.ide.studio.canvasModeEnabled` flag. I created a PR for you that should fix that  https://github.com/engageLively/galyleo-dashboard/pull/168/files
