### ISSUE TITLE
style not getting applied to html morph

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#87]
Weird, because it was working before.  I fixed a bug in my code (per previous issue) and the table is fine but it's unstyled.  I've surrounded the HTML with div, and tried without, no difference...world is dataParser.

CSS is:
table {
  border: 1px solid #1C6EA4;
  background-color: #EEEEEE;
  width: 100%;
  text-align: left;
  border-collapse: collapse;
  overflow: auto;
}
table td, table th {
  border: 1px solid #AAAAAA;
  padding: 3px 2px;
}
table tbody td {
  font-size: 13px;
}
table tr:nth-child(even) {
  background: #D0E4F5;
}
table thead {
  background: #1C6EA4;
  background: -moz-linear-gradient(top, #5592bb 0%, #327cad 66%, #1C6EA4 100%);
  background: -webkit-linear-gradient(top, #5592bb 0%, #327cad 66%, #1C6EA4 100%);
  background: linear-gradient(to bottom, #5592bb 0%, #327cad 66%, #1C6EA4 100%);
  border-bottom: 2px solid #444444;
}
table thead th {
  font-size: 15px;
  font-weight: bold;
  color: #FFFFFF;
  border-left: 2px solid #D0E4F5;
}
table thead th:first-child {
  border-left: none;
}

table tfoot {
  font-size: 14px;
  font-weight: bold;
  color: #FFFFFF;
  background: #D0E4F5;
  background: -moz-linear-gradient(top, #dcebf7 0%, #d4e6f6 66%, #D0E4F5 100%);
  background: -webkit-linear-gradient(top, #dcebf7 0%, #d4e6f6 66%, #D0E4F5 100%);
  background: linear-gradient(to bottom, #dcebf7 0%, #d4e6f6 66%, #D0E4F5 100%);
  border-top: 2px solid #444444;
}
table tfoot td {
  font-size: 14px;
}
table tfoot .links {
  text-align: right;
}
table tfoot .links a{
  display: inline-block;
  background: #1C6EA4;
  color: #FFFFFF;
  padding: 2px 8px;
  border-r 2px 8px;
  border-radius: 5px;
}

HTML is:

<div>

<table>

<thead>
<tr>
<th>A</th>
<th>B</th>
<th>C</th>
</tr>
</thead>

<tbody>
<tr>
<td>1</td>
<td>2</td>
<td>3</td>
</tr>
<tr>
<td>11</td>
<td>12</td>
<td>13</td>
</tr>
<tr>
<td>21</td>
<td>22</td>
<td>23</td>
</tr>
<tr>
<td>31</td>
<td>32</td>
<td>33</td>
</tr>
<tr>
<td>41</td>
<td>42</td>
<td>43</td>
</tr>
<tr>
<td>51</td>
<td>52</td>
<td>53</td>
</tr>
<tr>
<td>61</td>
<td>62</td>
<td>63</td>
</tr>
<tr>
<td>71</td>
<td>72</td>
<td>73</td>
</tr>
<tr>
<td>81</td>
<td>82</td>
<td>83</td>
</tr>
<tr>
<td>91</td>
<td>92</td>
<td>93</td>
</tr>
</tbody>

</table>

</div>

**Comment by merryman** [comment]
There is a syntax error in the last line of your css: `border-r 2px 8px;` I will add syntax checking to the css editor soon.

**Comment by rickmcgeer** [comment]
Sorry....
