### ISSUE TITLE
Initial text measuring returns wrong values for Icons

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#872]
**Describe the bug**
The initial text measuring seems to return faulty values when Icons are contained in the text. This leads to cut-off icons, e.g. in the user flap in the top right in the top-bar.

**Screenshots**

![cutoff_icon](https://github.com/LivelyKernel/lively.next/assets/14252419/0fa94533-ea18-4d39-9406-8af55930d94f)

**Additional Information**

When calling `fit()` on the label after the fact, this problem goes away and the extent of the label changes quite drastically. When opening a label with an icon in the world, setting it to autofit and changing the fontsize, the icon also does not get cut. I therefore assume that the problem only lies with the initial measuring that happens "off-screen".

**Comment by linusha** [comment]
It seems just calling `fit` does indeed not cut it. For me, calling `fit` does not do anything. Instead, changing the `letterSpacing` to 1 resolves the problem, as for me the icon is cut off on the right side.
However, on @merrymans machine the cutoff happens on the left side.

**Comment by merryman** [comment]
@linusha Is this bug still a thing, or has it been resolved by our now asynchronous `fontFamily` handling, where we ensure that fonts are loaded before proceeding?

**Comment by linusha** [comment]
![image](https://github.com/LivelyKernel/lively.next/assets/14252419/cf7fe839-2f49-4053-bbac-9ac52239e94d)

Still happens :(
