### ISSUE TITLE
Allow updating from inside of lively.next

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#879]
**Describe the Feature**
Recently, we pushed multiple changes that required to rebuild the loading-screen and the landing-page of lively.next in addition to pulling the changes. This means, that lively end-users not only need to `git pull` to get the update, but then either execute `./install.sh` or `make artifacts` manually. As the end-users of lively should not only be programmers, but also designers or more general, people that do not want to interact with a CLI, this is suboptimal.

We should allow to update lively.next from within itself. For that, we need to present either a popup if lively detects that one is a) on `main` and b) `main` is behind `origin/main` or we should at least present a way to trigger the update via a GUI element (might be the time to add a more sophisticated "general" menu in the topbar).

The update process should take care of the following: 

1. Pull the latest `origin/main`
2. Rebuild the landing page and loading screen (if necessary?)
3. Run the deps installation for lively packages? 
4. Restart the server
5. Report when everything is up and running and probably reload :)

**Implementation Details**
It is important that we trigger everything we want to trigger via `lively.shell` before we kill the server.
When we killed the server, started bash commands should continue to run, so we can trigger a shell script that finds the currently running lively.server's PID, kills that and restarts the server.
We can then catch that a new server has started via the same mechanism that the green/red "online" lamp in the user flap uses.

**Open Questions**
This will result in a running lively server that runs in the background, e.g. is not attached to a shell. This is suboptimal, since now there is no clear way for end users to stop the server process.
Ideas: We could either fork inside of the "server" process, so that the actual server runs as a child. We could also think about deploying a watcher mechanism akin to `pm2` and others.

**Comment by merryman** [comment]
How about we steal a bit from already existing UIs that notify the user about pending updates? For instance we could place a small indicator next to the user flap, that indicates an update is possible and enabling the user to trigger the update from there in the way you described.
