### ISSUE TITLE
Convenience routine for Canvas

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#91]
The most efficient routine in Canvas is rect, which draws a rectangle.  I wrote the convenience methods in Canvas long ago, but forgot about this one; since it's now a core part of lively, this should go in, but it should probably someone who knows the whole codebase who does it.  The code is:
`rect(atPt, extent, style={}) {
    // this.rect(pt(20,20), pt(50,50), {fill: true, fillColor: Color.red})
    let c = this.context;
    c.beginPath();
    c.rect(atPt.x, atPt.y, extent.x, extent.y);
    this.finishDraw(style);
  }`

**Comment by merryman** [comment]
added in 42418e50ba85b414286cb40e1a6d5a86f11fef98
