### ISSUE TITLE
Tooltips persist

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#911]
**Describe the bug**
This happens on everything that brings up a Tooltip in lively -- the Tooltips are persistent for many seconds, obscuring the screen

**To Reproduce**
Hover over a Halo tool or anything in the browser, see the Tooltip come up, and see it not disappear

**Screenshots**
![image](https://github.com/LivelyKernel/lively.next/assets/656259/f862d9df-ccb8-4b76-a56e-ece265597282)

**Setup**
Please delete non-applicable items!

- Windows

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).
5cecb8d2030617b92320cefc9ea4e63439e36630

**Comment by rickmcgeer** [comment]
Reproduced on Mac

**Comment by merryman** [comment]
Looks like a resurfacing of https://github.com/LivelyKernel/lively.next/issues/764. Can you also reproduce the issues with the stuck halos?
