### ISSUE TITLE
Convenient access to HTML DOM Element for morph (suggestion)

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#93]
jexcel, like many JavaScript libraries, uses dom elements.  The way to create a jexcel table is to use the function jexcel, with the dom element as the first argument `jexcel(document.getElementById(),...`.  We can do this in morphic, but it's a little awkward.  I use the snippets @merryman gave me:
`get htmlRef() {
    // get a reference from plain html to this = test runner
    return `System.get(System.normalizeSync('lively.morphic')).MorphicEnv.default().world.getMorphWithId('${this.id}')`;
  }
  get htmlDiv() {
    return document.getElementById(this.id)
  }`
But I would think it's easier just to have this built in to Morph.

**Comment by linusha** [comment]
> jexcel(document.getElementById()

In these cases, one should most probably always use an `HTMLMorph`.
In other scenarios where one needs the DOM node of a morph, it is always accessible through the renderer.
