### ISSUE TITLE
Adding CSS to a world in a convenient way -- SUGGESTION

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#94]
Many libraries rely on having their own CSS as well (and we know that  this has been a request).  It seems to me (as an amateur, so _take this as a suggestion only_) that there's a convenient hack: Add the "Edit CSS" tag to the world menu, as well, and permit the use of external stylesheets as well as inline.  Then, for each morph, allow the class tag to be editable, since this is the primary way people use CSS.

**Comment by merryman** [comment]
@linusha I believe the way we currently handle css files in our project system works reasonably well? I dont know if we are planning on expanding support for this, but I believe the current system more or less covers what @rickmcgeer pointed out.
