### ISSUE TITLE
Error in listing local projects

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#944]
**Describe the bug**
This is related to #943 and in fact is probably a result of it.  When I have the new project `rickmcgeer--test1` in the local_projects folder, the dashboard hangs. Here's the console log:
```
Uncaught (in promise) Error: Error listing local projects
    at _callee14$ (landing-page.cp-a72aeadb.js:35009:26)
    at tryCatch (deps.js:684:40)
    at Generator.invoke [as _invoke] (deps.js:914:22)
    at Generator.next (deps.js:739:21)
    at asyncGeneratorStep (__rootModule___commonjs-entry-0a831cc3.js:166:30)
    at _next (__rootModule___commonjs-entry-0a831cc3.js:188:15)
```

**To Reproduce**
Steps to reproduce the behavior. Please make sure to let us know if your problem requires the loading of custom components,...

**Screenshots**
![image](https://github.com/LivelyKernel/lively.next/assets/656259/b7c42cbf-82bc-48ac-82a2-292daf1aceca)

**Setup**
Please delete non-applicable items!

- Windows
- Linux

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).
89e6003509edfbeeb9deceadaebabf82903dbe60

**Comment by merryman** [comment]
This is because you have a non initialized git repository in one of your projects which is due to a severely outdated git version on WSL.

**Comment by rickmcgeer** [comment]
I'll leave it closed, but according to apt-get I'm running the latest version of git (2.25.1).  So I suspect this is due to #943.  In any case, if there are external dependencies, can we pull together a Dockerfile with the right dependencies installed?
