### ISSUE TITLE
Intermittent problem loading jexcel

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#95]
It works sometimes, but most of the time I seem to be getting a 404 downloading jexcel.  This is probably something to do with jspm and not us.  It happens with jexcel@4.4.1 and jexcel3@1.0.1
![image](https://user-images.githubusercontent.com/656259/99324652-98f69880-2829-11eb-8ab0-b67ce59c244d.png)

**Comment by merryman** [comment]
Indeed, this is a problem with jspm itself: https://jspm.org/sandbox#H4sIAAAAAAAAAyWMQRKCMAwA731F5IJeqGco/Yu2EcokpNNGR36vTK+7O+suUYIeGWFVJm/cU+IBVQ/CmR9lSft4986e9C9rKCkrnP3cscQ3YedN4ixFYcNvQIJXEYZ+Vc11tHarmYeIH9tsP5kgexXCgWS5NnibjLNt7c0P5h+3WJEAAAA=
It appears to be related to css modules. I filed a ticket for that in their help channel.

**Comment by merryman** [comment]
Update: It seems like there is no support from css modules from jspm for now. I added a skipping mechanism for now, that will ignore css modules and make the import still happen, which should most of the time be fine. However you need to then make sure that the styles required by the library are loaded.
