### ISSUE TITLE
Menu is not clickable behind morph

### ISSUE THREAD

**Issue by frcroth** [LivelyKernel/lively.next#96]
When creating a rectangle morph and right clicking into it to open a context menu, some menu items are visible but not clickable. This seems counter intuitive.

![vokoscreenNG-2020-11-17-09-33-45](https://user-images.githubusercontent.com/6863832/99366275-ac047980-28b8-11eb-855a-c2aad6130d26.gif)

**Comment by merryman** [comment]
Fixed in 9a2e989c06610e9685a40a353264f2a45a60be3c
