### ISSUE TITLE
Clicking on "Scene Graph" tab (left side of main window) does nothing

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#971]
**Describe the bug**
Clicking on the Scene Graph tab does nothing  -- the scene graph does not appear.  When I checked the console log, I saw this:
```
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'renderedMorphs')
    at eval (morph.js:1051:58)
    at ChangeManager.ChangeManager_groupChangesWhile_ (changes.js:416:17)
    at Morph.Morph_groupChangesWhile_ (morph.js:651:45)
    at ChangeManager.ChangeManager_addMethodCallChangeDoing_ (changes.js:378:21)
    at Morph.Morph_addMethodCallChangeDoing_ (morph.js:645:45)
    at Morph.Morph_addMorphAt_ (morph.js:1029:20)
    at Morph.Morph_addMorph_ (morph.js:1084:27)
    at eval (morph.js:3057:84)
    at Array.forEach (<anonymous>)
    at Morph.set [as submorphs] (morph.js:3057:34)
```
This occurred in both an empty world and one with morphs in it.

**To Reproduce**
Steps to reproduce the behavior. Please make sure to let us know if your problem requires the loading of custom components,...

**Screenshots**

**Setup**
Please delete non-applicable items!

- Windows
- Linux

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).
34f27b39a9805265b86369a67ee0ffe665dc1f8e

**Comment by rickmcgeer** [comment]
Like #972, this disappeared in a new window.

**Comment by rickmcgeer** [comment]
So I think the key to reproducing this is to resize the browser window after the project has been loaded.

**Comment by linusha** [comment]
I cannot reproduce this. I am not sure how, but it might be that the constantly failing font measuring trips this up as well.

Could you try reproducing this once we have the font problem sorted out?

**Comment by linusha** [comment]
I assume this was related to a missing rebuild after we changed the font inclusion mechanism. @rickmcgeer please reopen if the problem persists.
