### ISSUE TITLE
Javascript workspace cursor is misaligned

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#973]
**Describe the bug**
After I pasted the following code into a JavaScript workspace:
```
new VideoMorph({
      src: 'https://matt.engagelively.com/assets/ITF/Ibn_Map_100.mp4',
      type: 'video/mp4',
      extent: pt(1920, 1080),
      position: pt(0, 0),
      name: 'ibn'
    });
```
and then used a `Fix undeclared variables` to automatically add these two lines to the top:
```
import { VideoMorph } from "lively.components/video.js";
import { pt } from "lively.graphics";
```
Every evaluation had a syntax error and code was changing two lines above where the cursor was when I typed.  You can see the misalignment in the attached screenshot; I had just typed 'foo.', and the cursor is the red line you see two lines below the last line typed.

**To Reproduce**
Steps to reproduce the behavior. Please make sure to let us know if your problem requires the loading of custom components,...

**Screenshots**
![image](https://github.com/LivelyKernel/lively.next/assets/656259/8e47c65b-ed3e-4fa2-98de-311d9f44e00e)

**Setup**
Please delete non-applicable items!

- Windows
- Linux

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).
34f27b39a9805265b86369a67ee0ffe665dc1f8e

**Comment by linusha** [comment]
I assume this was related to a missing rebuild after we changed the font inclusion mechanism. @rickmcgeer please reopen if the problem persists.
