### ISSUE TITLE
Scene graph morph expansion is very flaky

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#975]
**Describe the bug**
When I open the scene graph, the usual icon to the left of a morph is replaced with a square.  At the top level, clicking on the square shows the next-level morph, but further expansion doesn't work.  If I had to guess, I'd guess the wrong morph is picking up the Mouse event, since a rectangle appears around the morph name

**To Reproduce**
Steps to reproduce the behavior. Please make sure to let us know if your problem requires the loading of custom components,...

**Screenshots**
![image](https://github.com/LivelyKernel/lively.next/assets/656259/d2c8638f-883c-4d02-850c-223e236a3f2c)

**Setup**
Please delete non-applicable items!

- Windows
- Linux

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).
34f27b39a9805265b86369a67ee0ffe665dc1f8e

**Comment by linusha** [comment]
I assume this was related to a missing rebuild after we changed the font inclusion mechanism. @rickmcgeer please reopen if the problem persists.
