### ISSUE TITLE
Halos are offset for components with layouts and active `ViewModel`

### ISSUE THREAD

**Issue by linusha** [LivelyKernel/lively.next#990]
**Describe the bug**
When designing a component, the halos are working fine. Activating the behavior of the component lead to the halo being offset. It might be related to the fact that the component that I edited is a prompt, although that is not certain.

**Screenshots**

https://github.com/LivelyKernel/lively.next/assets/14252419/a9b8da93-b7aa-436a-884d-02b352cf6152

**Version**: a1df97742c7848bebcabda2aa699b4de19b3dbcd

**Comment by merryman** [comment]
This will be handled by #1042.
